INSERT INTO EXERCISE_DETAILS ("id", "name", "pic_url", "mechanics", "force", "primary_body_part", "secondary_body_part" ,"equipment_1", "equipment_2")
    VALUES ('close-grip-push-up', 'Close-grip Push-up','close-grip-push-up.png','compound', 'push','arms', 'chest', null, null),
           ('bent-knee-bench-dip', 'Bent-knee Bench Dip','bent-knee-bench-dip.png','compound', 'push','arms', 'chest', 'bench', null),
           ('barbell-preacher-curl', 'Barbell Preacher Curl','barbell-preacher-curl.png','isolation', 'pull', 'arms', null, 'preacher curl bench', 'dumbbells'),
           ('barbell-drag-curl', 'Barbell Drag Curl', 'barbell-drag-curl.png', 'isolation', 'pull', 'arms', null, 'barbell', null),
           ('barbell-rear-delt-row', 'Barbell Rear Delt Row', 'barbell-rear-delt-row.png', 'compound', 'pull', 'shoulders', 'arms', 'barbell', null),
           ('weighted-pull-up', 'Weighted pull-up', 'weighted-pull-up.png', 'compound', 'pull', 'back', 'arms', 'pull-up bar', 'weight plate'),
           ('barbell-underhand-grip-bent-over-row', 'Barbell Underhand-grip Bent-over Row', 'barbell-underhand-grip-bent-over-row.png', 'compound', 'pull', 'back', 'arms', 'barbell', null),
           ('one-arm-knee-push-up', 'One-arm Knee Push-up', 'one-arm-knee-push-up.png', 'compound', 'push', 'chest', 'arms', null, null),
           ('incline-dumbbell-hammer-curl', 'Incline Dumbbell Hammer Curl', 'incline-dumbbell-hammer-curl.png', 'isolation', 'pull', 'arms', null, 'dumbbells', null),
           ('standing-dumbbell-kickback', 'Standing Dumbbell Kickback', 'standing-dumbbell-kickback.png', 'isolation', 'push', 'arms', null, 'dumbbells', null),
           ('incline-dumbbell-curl', 'Incline Dumbbell Curl', 'incline-dumbbell-curl.png', 'isolation', 'pull', 'arms', null, 'incline bench', 'dumbbells'),
           ('incline-dumbbell-inner-biceps-curl', 'incline Dumbbell Inner-biceps Curl', 'incline-dumbbell-inner-biceps-curl.png', 'isolation', 'pull', 'arms', null, 'incline bench', 'dumbbells'),
           ('decline-dumbbell-triceps-extension', 'Decline Dumbbell Triceps Extension', 'decline-dumbbell-triceps-extension.png', 'isolation', 'push', 'arms', null, 'decline bench', 'dumbbells'),
           ('cable-rear-drive', 'Cable Rear Drive', 'cable-rear-drive.png', 'compound', 'push', 'arms', 'shoulders', 'cable machine', null),
           ('seated-dumbbell-wrist-curl', 'Seated Dumbbell Wrist Curl', 'seated-dumbbell-wrist-curl.png', 'isolation', 'pull', 'arms', null, 'dumbbells', null),
           ('close-grip-barbell-bench-press', 'Close-grip Barbell Bench Press', 'close-grip-barbell-bench-press.png', 'compound', 'push', 'arms', 'chest', 'press bench', 'barbell'),
           ('standing-dumbbell-preacher-curl', 'Standing Dumbbell Preacher Curl', 'standing-dumbbell-preacher-curl.png', 'isolation', 'pull', 'arms', null, 'incline bench', 'dumbbells'),
           ('seated-dumbbell-overhead-triceps-extension', 'Seated Dumbbell Overhead Triceps Extension', 'seated-dumbbell-overhead-triceps-extension.png', 'isolation', 'push', 'arms', null, 'dumbbells', null),
           ('dumbbell-reverse-curl', 'Dumbbell Reverse Curl', 'dumbbell-reverse-curl.png', 'isolation', 'pull', 'arms', null, 'dumbbells', null),
           ('ez-bar-reverse-curl', 'EZ Bar Reverse Curl', 'ez-bar-reverse-curl.png', 'isolation', 'pull', 'arms', null, 'EZ bar', null),
           ('arnold-press', 'Arnold Press', 'arnold-press.png', 'compound', 'push', 'shoulders', null, 'dumbbells', null),
           ('dumbbell-lateral-raise', 'Dumbbell Lateral Raise', 'dumbbell-lateral-raise.png', 'isolation', 'pull', 'shoulders', null, 'dumbbells', null),
           ('bent-over-lateral-raise', 'Bent-over Lateral Raise', 'bent-over-lateral-raise.png', 'isolation', 'pull', 'shoulders', 'back', 'dumbbells', null),
           ('cable-external-shoulder-rotation', 'cable-external-shoulder-rotation', 'cable-external-shoulder-rotation.png', 'isolation', 'pull', 'shoulders', null, 'cable machine', null),
           ('cable-one-arm-lateral-raise', 'Cable One-arm Lateral Raise', 'cable-one-arm-lateral-raise.png', 'isolation', 'pull', 'shoulders', null, 'cable machine', null),
           ('seated-dumbbell-lateral-raise', 'Seated Dumbbell Lateral Raise', 'seated-dumbbell-lateral-raise.png', 'isolation', 'pull', 'shoulders', null, 'dumbbells', null),
           ('plate-front-raise', 'Plate Front Raise', 'plate-front-raise.png', 'isolation', 'push', 'shoulders', null, 'weight plate', null),
           ('dumbbell-one-arm-upright-row', 'Dumbbell One-arm Upright Row', 'dumbbell-one-arm-upright-row.png', 'compound', 'pull', 'shoulders', 'arms', 'dumbbells', null),
           ('seated-dumbbell-one-arm-shoulder-press', 'Seated Dumbbell One-arm Shoulder Press', 'seated-dumbbell-one-arm-shoulder-press.png', 'compound', 'push', 'shoulders', null, 'dumbbells', null),
           ('one-arm-dumbbell-bent-over-lateral-raise', 'One-arm Dumbbell Bent-over Lateral Raise', 'one-arm-dumbbell-bent-over-lateral-raise.png', 'isolation', 'pull', 'shoulders', null, 'dumbbells', null),
//30 arms and shoulders (30)
           ('triceps-dip', 'Triceps Dip', 'triceps-dip.png', 'compound', 'push', 'arms', 'chest', 'dip stand', null),
           ('bench-press', 'Bench Press', 'bench-press.png', 'compound', 'push', 'chest', null, 'press bench', null),
           ('cable-cross-over', 'Standing Cable Fly', 'cable-cross-over.png', 'isolation', 'push', 'chest', null, 'cable machine', null),
           ('low-cable-cross-over', 'Standing incline cable fly', 'low-cable-cross-over.png', 'isolation', 'push', 'chest', null, 'cable machine', null),
           ('decline-barbell-bench-press', 'Decline Barbell Bench Press', 'decline-barbell-bench-press.png', 'compound', 'push', 'chest', null, 'decline bench', 'barbell'),
           ('incline-barbell-bench-press', 'Incline Barbell Bench Press', 'incline-barbell-bench-press.png', 'compound', 'push', 'chest', null, 'incline bench', 'barbell'),
           ('incline-dumbbell-bench-press', 'Incline Dumbbell Bench Press', 'incline-dumbbell-bench-press.png', 'compound', 'push', 'chest', null, 'incline bench', 'dumbbells'),
           ('dumbbell-fly', 'Dumbbell Fly', 'dumbbell-fly.png', 'isolation', 'push', 'chest', null, 'dumbbells', null),
           ('machine-fly', 'Machine Fly', 'machine-fly.png', 'isolation', 'push', 'chest', null, 'fly machine', null),
           ('svend-press', 'Svend Press', 'svend-press.png', 'compound', 'push', 'chest', null, 'weight plate', null),
           ('isometric-wiper', 'Isometric Wiper', 'isometric-wiper.png', 'compound', 'push', 'chest', null, null, null),
           ('hammer-grip-dumbbell-bench-press', 'Hammer-grip Dumbbell Bench Press', 'hammer-grip-dumbbell-bench-press.png', 'compound', 'push', 'chest', null, 'dumbbells', null),
           ('decline-dumbbell-fly', 'Decline Dumbbell Fly', 'decline-dumbbell-fly.png', 'isolation', 'push', 'chest', null, 'decline bench', 'dumbbells'),
           ('decline-dumbbell-bench-press', 'Decline Dumbbell Bench Press', 'decline-dumbbell-bench-press.png', 'compound', 'push', 'chest', null, 'decline bench', 'dumbbells'),
           ('incline-dumbbell-fly', 'Incline Dumbbell Fly', 'incline-dumbbell-fly.png', 'isolation', 'push', 'chest', null, 'incline bench', 'dumbbells'),
           ('barbell-jm-press', 'Barbell JM Press', 'barbell-jm-press.png', 'compound', 'push', 'arms', 'chest', 'press bench', 'barbell'),
           ('incline-dumbbell-press-on-a-stability-ball', 'Incline Dumbbell Press On a Stability Ball', 'incline-dumbbell-press-on-a-stability-ball.png', 'compound', 'push', 'chest', null, 'stability ball', 'dumbbells'),
           ('wide-reverse-grip-barbell-bench-press', 'Wide Reverse-grip Barbell Bench Press', 'wide-reverse-grip-barbell-bench-press.png', 'compound', 'push', 'chest', null, 'press bench', 'barbell'),
           ('dumbbell-press-on-a-stability-ball', 'Dumbbell Press On a Stability Ball', 'dumbbell-press-on-a-stability-ball.png', 'compound', 'push', 'chest', null, 'stability ball', 'dumbbells'),
//19 chest (49)
           ('barbell-deadlift', 'Barbell Deadlift', 'barbell-deadlift.png', 'compound', 'pull', 'back', 'legs', 'barbell', null),
           ('dumbbell-pullover', 'dumbbell-pullover', 'dumbbell-pullover.png', 'isolation', 'push', 'chest', 'back', 'bench', 'dumbbells'),
           ('bent-over-dumbbell-row', 'Bent-over Dumbbell Row', 'bent-over-dumbbell-row.png', 'compound', 'pull', 'back', null, 'dumbbells', null),
           ('pull-up', 'Pull-up', 'pull-up.png', 'compound', 'pull', 'back', 'arms', 'pull-up bar', null),
           ('dumbbell-shrug', 'Dumbbell Shrug', 'dumbbell-shrug.png', 'isolation', 'pull', 'back', null, 'dumbbells', null),
           ('inverted-row', 'Inverted Row', 'inverted-row.png', 'compound', 'pull', 'back', null, 'smith machine', null),
           ('bent-over-two-arm-dumbbell-row', 'Bent-over Two-arm Dumbbell Row', 'bent-over-two-arm-dumbbell-row.png', 'compound', 'pull', 'back', null, 'dumbbells', null),
           ('barbell-sumo-deadlift', 'Barbell Sumo Deadlift', 'barbell-sumo-deadlift.png', 'compound', 'pull', 'back', 'legs', 'barbell', null),
           ('bent-over-one-arm-cable-pull', 'Bent-over One-arm Cable Pull', 'bent-over-one-arm-cable-pull.png', 'compound', 'pull', 'back', null, 'cable machine', null),
           ('one-arm-lat-pull-down', 'One-arm Lat Pull-down', 'one-arm-lat-pull-down.png', 'compound', 'pull', 'back', 'arms', 'cable machine', null),
           ('seated-twisting-cable-row', 'Seated Twisting Cable Row', 'seated-twisting-cable-row.png', 'compound', 'pull','back', 'arms', 'cable machine', null),
           ('standing-twisting-cable-high-row', 'Standing Twisting Cable High Row', 'standing-twisting-cable-high-row.png', 'compound', 'pull', 'back', 'core', 'cable machine', null),
           ('rope-lat-pull-down', 'Rope Lat Pull-down', 'rope-lat-pull-down.png', 'compound', 'pull', 'back', 'arms', 'cable machine', null),
           ('standing-cable-row', 'Standing Cable Row', 'standing-cable-row.png', 'compound', 'pull', 'back', null, 'cable machine', null),
           ('barbell-good-morning', 'Barbell Good Morning', 'barbell-good-morning.png', 'isolation', 'pull', 'back', 'glutes', 'barbell', null),
           ('barbell-bent-knee-good-morning', 'Barbell Bent-knee Good Morning', 'barbell-bent-knee-good-morning.png', 'isolation', 'pull', 'back', 'legs', 'barbell', null),
           ('barbell-sumo-romanian-deadlift', 'Barbell Sumo Romanian Deadlift', 'barbell-sumo-romanian-deadlift.png', 'compound', 'pull', 'back', 'legs', 'barbell', null),
           ('chin-up', 'Chin-up', 'chin-up.png', 'compound', 'pull', 'back', 'arms', 'pull-up bar', null),
           ('dumbbell-straight-leg-deadlift', 'Dumbbell Straight-leg Deadlift', 'dumbbell-straight-leg-deadlift.png', 'compound', 'pull', 'back', 'glutes', 'dumbbells', null),
           ('kettlebell-deadlift', 'Kettlebell Deadlift', 'kettlebell-deadlift.png', 'compound', 'pull', 'back', 'legs', 'kettlebell', null),
//20 back (69)
           ('leg-extension', 'Leg Extension', 'leg-extension.png', 'isolation', 'push', 'legs', null, 'leg extension machine', null),
           ('wheel-rollout', 'Wheel Rollout', 'wheel-rollout.png', 'compound', 'pull', 'core', 'legs', 'wheel', null),
           ('one-arm-bench-dip', 'One-arm Bench Dip', 'one-arm-bench-dip.png', 'compound', 'push', 'arms', 'legs', 'bench', null),
           ('barbell-sumo-squat', 'Barbell Sumo Squat', 'barbell-sumo-squat.png', 'compound', 'push', 'legs', null, 'barbell', null),
           ('weighted-one-leg-hip-thrust', 'Weighted One-leg Hip Thrust', 'weighted-one-leg-hip-thrust.png', 'isolation', 'push', 'glutes', 'legs', 'bench', 'weight plate'),
           ('bodyweight-squat', 'Bodyweight Squat', 'bodyweight-squat.png', 'compound', 'push', 'legs', 'glutes', null, null),
           ('lunge', 'Lunge', 'lunge.png', 'compound', 'push', 'legs', 'glutes', null, null),
           ('dumbbell-box-squat', 'Dumbbell Box Squat', 'dumbbell-box-squat.png', 'compound', 'push', 'legs', 'glutes', 'dumbbells', 'bench'),
           ('smith-machine-squat', 'Smith Machine Squat', 'smith-machine-squat.png', 'compound', 'push', 'legs', 'glutes', 'smith machine', null),
           ('seated-dumbbell-one-leg-calf-raise', 'Seated Dumbbell One-leg Calf Rise', 'seated-dumbbell-one-leg-calf-raise.png', 'isolation', 'push', 'legs', null, 'dumbbells', null),
           ('dumbbell-overhead-squat', 'Dumbbell Overhead Squat', 'dumbbell-overhead-squat.png', 'compound', 'push', 'legs', 'core', 'dumbbells', null),
           ('bulgarian-split-squat', 'Bulgarian Split Squat', 'bulgarian-split-squat.png', 'compound', 'push', 'legs', null, 'bench', null),
           ('one-leg-hip-thrust', 'One-leg Hip Thrust', 'one-leg-hip-thrust.png', 'isolation', 'push', 'glutes', 'legs', 'bench', null),
           ('double-kettlebell-front-squat', 'Double Kettlebell Front Squat', 'double-kettlebell-front-squat.png', 'compound', 'push', 'legs', 'glutes', 'kettlebell', null),
           ('dumbbell-goblet-split-squat', 'Dumbbell Goblet Split Squat', 'dumbbell-goblet-split-squat.png', 'compound', 'push', 'legs', 'glutes', 'dumbbells', null),
//15 legs and glutes (84)
           ('sit-up', 'Sit-up', 'sit-up.png', 'compound', 'pull', 'core', null, null, null),
           ('crunch', 'Crunch', 'crunch.png', 'isolation', 'pull', 'core', null, null, null),
           ('front-plank', 'Front Plank', 'front-plank.png', 'isolation', 'push', 'core', null, null, null),
           ('lying-side-hip-raise', 'Lying Side Hip Raise', 'lying-side-hip-raise.png', 'isolation', 'push', 'core', 'legs', null, null),
           ('weighted-hanging-leg-and-hip-raise', 'Weighted Hanging Leg And Hip Raise', 'weighted-hanging-leg-and-hip-raise.png', 'compound', 'pull', 'core', null, 'pull-up bar', 'dumbbells'),
           ('frog-crunch', 'Frog Crunch', 'frog-crunch.png', 'isolation', 'pull', 'core', null, null, null),
           ('frog-crunch-with-leg-raise', 'Frog Crunch With Leg Raise', 'frog-crunch-with-leg-raise.png', 'compound', 'pull', 'core', null, null, null),
           ('bent-knee-oblique-v-up', 'Bent-knee Oblique V-up', 'bent-knee-oblique-v-up.png', 'isolation', 'pull', 'core', null, null, null),
           ('side-plank-hip-adduction', 'Side Plank Hip Adduction', 'side-plank-hip-adduction.png', 'compound', 'pull', 'core', 'legs', 'bench', null),
           ('hanging-leg-hip-raise', 'Hanging Leg Hip Raise', 'hanging-leg-hip-raise.png', 'compound', 'pull', 'core', null, 'pull-up bar', null)
//10 core (94)
           ;

INSERT INTO TARGET_MUSCLES ("exercise_id", "muscle")
    VALUES ('close-grip-push-up', 'Triceps Brachii' ),
           ('bent-knee-bench-dip', 'Triceps Brachii' ),
           ('barbell-preacher-curl', 'Brachialis'),
           ('barbell-drag-curl', 'Biceps Brachii'),
           ('barbell-rear-delt-row', 'Posterior Deltoid'),
           ('weighted-pull-up', 'Latissimus Dorsi'),
           ('barbell-underhand-grip-bent-over-row', 'Latissimus Dorsi'),
           ('barbell-underhand-grip-bent-over-row', 'Teres Major'),
           ('barbell-underhand-grip-bent-over-row', 'Rhomboids'),
           ('one-arm-knee-push-up', 'Lower Pectoralis Major'),
           ('incline-dumbbell-hammer-curl', 'Brachioradialis'),
           ('standing-dumbbell-kickback', 'Triceps Brachii'),
           ('incline-dumbbell-curl', 'Biceps Brachii'),
           ('incline-dumbbell-inner-biceps-curl', 'Brachialis'),
           ('decline-dumbbell-triceps-extension', 'Triceps Brachii'),
           ('cable-rear-drive', 'Triceps Brachii'),
           ('cable-rear-drive', 'Posterior Deltoid'),
           ('seated-dumbbell-wrist-curl', 'Wrist Flexors'),
           ('close-grip-barbell-bench-press', 'Triceps Brachii'),
           ('standing-dumbbell-preacher-curl', 'Brachialis'),
           ('seated-dumbbell-overhead-triceps-extension', 'Triceps Brachii'),
           ('dumbbell-reverse-curl', 'Brachioradialis'),
           ('ez-bar-reverse-curl', 'Brachioradialis'),
           ('arnold-press', 'Anterior Deltoid'),
           ('dumbbell-lateral-raise', 'Lateral Deltoid'),
           ('bent-over-lateral-raise', 'Posterior Deltoid'),
           ('cable-external-shoulder-rotation', 'Infraspinatus'),
           ('cable-one-arm-lateral-raise', 'Lateral Deltoid'),
           ('seated-dumbbell-lateral-raise', 'Lateral Deltoid'),
           ('plate-front-raise', 'Anterior Deltoid'),
           ('dumbbell-one-arm-upright-row', 'Lateral Deltoid'),
           ('seated-dumbbell-one-arm-shoulder-press', 'Anterior Deltoid'),
           ('one-arm-dumbbell-bent-over-lateral-raise', 'Posterior Deltoid'),
           ('triceps-dip', 'Triceps Brachii'),
           ('bench-press', 'Lower Pectoralis Major'),
           ('cable-cross-over', 'Lower Pectoralis Major'),
           ('low-cable-cross-over', 'Upper Pectoralis Major'),
           ('decline-barbell-bench-press', 'Lower Pectoralis Major'),
           ('incline-barbell-bench-press', 'Upper Pectoralis Major'),
           ('incline-dumbbell-bench-press', 'Upper Pectoralis Major'),
           ('dumbbell-fly', 'Lower Pectoralis Major'),
           ('machine-fly', 'Lower Pectoralis Major'),
           ('svend-press', 'Lower Pectoralis Major'),
           ('isometric-wiper', 'Lower Pectoralis Major'),
           ('hammer-grip-dumbbell-bench-press', 'Lower Pectoralis Major'),
           ('decline-dumbbell-fly', 'Lower Pectoralis Major'),
           ('decline-dumbbell-bench-press', 'Lower Pectoralis Major'),
           ('bent-knee-bench-dip', 'Triceps Brachii'),
           ('incline-dumbbell-fly', 'Upper Pectoralis Major'),
           ('barbell-jm-press', 'Triceps Brachii'),
           ('incline-dumbbell-press-on-a-stability-ball', 'Upper Pectoralis Major'),
           ('wide-reverse-grip-barbell-bench-press', 'Upper Pectoralis Major'),
           ('dumbbell-press-on-a-stability-ball', 'Lower Pectoralis Major'),
           ('barbell-deadlift', 'Gluteus Maximus'),
           ('barbell-deadlift', 'Erector Spinae'),
           ('dumbbell-pullover', 'Lower Pectoralis Major'),
           ('bent-over-dumbbell-row', 'Latissimus Dorsi'),
           ('bent-over-dumbbell-row', 'Teres Major'),
           ('pull-up', 'Latissimus Dorsi'),
           ('dumbbell-shrug', 'Upper Trapezius'),
           ('inverted-row', 'back in general'),
           ('bent-over-two-arm-dumbbell-row', 'back in general'),
           ('barbell-sumo-deadlift', 'Gluteus Maximus'),
           ('barbell-sumo-deadlift', 'Erector Spinae'),
           ('bent-over-one-arm-cable-pull', 'Latissimus Dorsi'),
           ('one-arm-lat-pull-down', 'Latissimus Dorsi'),
           ('seated-twisting-cable-row', 'back in general'),
           ('standing-twisting-cable-high-row', 'back in general'),
           ('rope-lat-pull-down', 'Latissimus Dorsi'),
           ('standing-cable-row', 'back in general'),
           ('barbell-good-morning', 'Hamstrings'),
           ('barbell-bent-knee-good-morning', 'Gluteus Maximus'),
           ('barbell-sumo-romanian-deadlift', 'Gluteus Maximus'),
           ('barbell-sumo-romanian-deadlift', 'Erector Spinae'),
           ('chin-up', 'Latissimus Dorsi'),
           ('kettlebell-deadlift', 'Gluteus Maximus'),
           ('leg-extension', 'Quadriceps'),
           ('wheel-rollout', 'Iliopsoas'),
           ('one-arm-bench-dip', 'Triceps Brachii'),
           ('one-arm-bench-dip', 'Quadriceps'),
           ('barbell-sumo-squat', 'legs in general'),
           ('weighted-one-leg-hip-thrust', 'Gluteus Maximus'),
           ('bodyweight-squat', 'legs in general'),
           ('lunge', 'quadriceps'),
           ('dumbbell-box-squat', 'Quadriceps'),
           ('smith-machine-squat', 'legs in general'),
           ('seated-dumbbell-one-leg-calf-raise', 'Soleus'),
           ('dumbbell-overhead-squat', 'legs in general'),
           ('bulgarian-split-squat', 'legs in general'),
           ('one-leg-hip-thrust', 'Gluteus Maximus'),
           ('double-kettlebell-front-squat', 'Quadriceps'),
           ('dumbbell-goblet-split-squat', 'Quadriceps'),
           ('sit-up', 'Rectus Abdominis'),
           ('crunch', 'Rectus Abdominis'),
           ('front-plank', 'Rectus Abdominis'),
           ('lying-side-hip-raise', 'Obliques'),
           ('weighted-hanging-leg-and-hip-raise', 'Rectus Abdominis'),
           ('frog-crunch', 'Rectus Abdominis'),
           ('frog-crunch-with-leg-raise', 'Rectus Abdominis'),
           ('frog-crunch-with-leg-raise', 'Iliopsoas'),
           ('bent-knee-oblique-v-up', 'Obliques'),
           ('side-plank-hip-adduction', 'Abductor'),
           ('hanging-leg-hip-raise', 'Rectus Abdominis'),
           ('dumbbell-straight-leg-deadlift', 'Erector Spinae'),
           ('dumbbell-straight-leg-deadlift', 'Hamstrings');



