INSERT INTO TIPS ("exercise_id", "id", "tip")
    VALUES ('close-grip-push-up', 1, 'To make the close-grip push-up easier, do it on your knees, or place your hands on the edge of an elevated surface, such as a bench or even a table'),
           ('close-grip-push-up', 2, 'To make the exercise more difficult, either wear a weighted vest, load a chain around your torso, or position your hands closer together.'),
           ('close-grip-push-up', 3, 'The most difficult unloaded variation of the close-grip push-up is the triangle or diamond push-up, which involves positioning your hands so close together as to form a diamond shape with your fingers and thumbs.'),
           ('close-grip-push-up', 4, 'To get your core more involved, perform the close-grip push-up on a medicine ball (see the fourth video). This exercise is more properly known as the medicine ball push-up.'),
           ('close-grip-push-up', 5, 'For beginners, try the close-grip push-up on knees.'),

           ('bent-knee-bench-dip', 1, 'Do not lower your body beyond feeling a mild stretch in your shoulders.'),
           ('bent-knee-bench-dip', 2, 'The point of keeping your torso upright and your elbows close to your body is to keep the emphasis on your triceps brachii instead of on your pectoralis major.'),
           ('bent-knee-bench-dip', 3, 'Make the bent-knee bench dip more difficult by extending your legs farther out.'),
           ('bent-knee-bench-dip', 4, 'See also the bench dip and the triceps dip.'),

           ('barbell-preacher-curl', 1, 'Adjust the seat to ensure that your upper arms, from armpits to elbows, lie flat on the padded surface of the preacher bench.'),
           ('barbell-preacher-curl', 2, 'Keep your elbows in line with your shoulders.'),
           ('barbell-preacher-curl', 3, 'Keep your body still. Only your forearms should move.'),
           ('barbell-preacher-curl', 4, 'When you perform the barbell preacher curl, the short (inner) head of your biceps brachii enters into active insufficiency (i.e. develops slack) at the top of the curl, Therefore, the long (outer) head of your biceps brachii is activated more than is the short head.'),
           ('barbell-preacher-curl', 5, 'Using an EZ bar might be easier on your wrists.'),
           ('barbell-preacher-curl', 6, 'See also the cable preacher curl and the dumbbell preacher curl.'),

           ('barbell-drag-curl', 1, 'Just like the name implies, the barbell is kept close to the body throughout the exercise, as if being dragged up and down its surface.'),
           ('barbell-drag-curl', 2, 'In addition to elbow flexion, the barbell drag curl incorporates shoulder hyperextension (when the elbows move backward), which activates the posterior deltoid. However, the activation of the posterior deltoid is relatively small, even under heavy load, so the effect of the barbell drag curl on posterior deltoid development is minimal.'),
           ('barbell-drag-curl', 3, 'Even though the exercise incorporates both elbow flexion and shoulder hyperextension, it is still considered an isolation exercise as opposed to a compound exercise because the extent of the shoulder hyperextension is small.'),
           ('barbell-drag-curl', 4, 'The long head of the biceps brachii is activated more than the short head is because, when the elbows move backward, the long head is stretched more than the short head is, allowing the long head to make more of a contribution to the lift.'),
           ('barbell-drag-curl', 5, 'See the incline dumbbell curl for another exercise that emphasizes the long head of the biceps brachii.'),

           ('barbell-rear-delt-row', 1, 'To target the posterior deltoids, your elbows must be kept perpendicular to your torso. This allows horizontal shoulder extension, the movement pattern in which the posterior deltoid is the primary mover. Learn more about horizontal pulling exercises in which you keep your elbows perpendicular to your torso.'),
           ('barbell-rear-delt-row', 2, 'Keep your torso horizontal and still; only your arms should move. This prevents cheating and keeps the focus on the target and synergistic muscles.'),
           ('barbell-rear-delt-row', 3, 'If your lower back becomes rounded, bend your knees more. Prioritize good form as this reduces the risk of lower back injury.'),
           ('barbell-rear-delt-row', 4, 'To target your posterior deltoids, you can also look into the bent-over barbell reverse raise and the standing cable rear delt row with rope.'),

           ('weighted-pull-up', 1, 'Pull with your elbows, not with your biceps.'),
           ('weighted-pull-up', 2, 'If you do not have access to a dip belt, you may perform the weighted pull-up with a dumbbell held between your feet.'),
           ('weighted-pull-up', 3, 'The weighted pull-up is an advanced exercise. You must gradually build your strength to get to the point where you can perform the exercise. Be sure that you have first mastered the pull-up. If you are having difficulty performing the pull-up, consider building your strength using the machine-assisted pull-up.'),
           ('weighted-pull-up', 4, 'The weighted pull-up is a major compound vertical pulling exercise. While it targets the latissimus dorsi, it recruits several other upper-body muscles as synergists. Thus, this exercise is great for developing upper-body size and strength.'),
           ('weighted-pull-up', 5, 'You may also look into the close neutral-grip pull-up and the self-assisted pull-up.'),

           ('barbell-underhand-grip-bent-over-row', 1, 'The barbell underhand-grip bent-over row is great for building your back (especially your latissimus dorsi) and elbow flexors, while strengthening your lower back, which has to support your whole upper body and the weight of the barbell.'),
           ('barbell-underhand-grip-bent-over-row', 2, 'Your torso must be parallel with the floor throughout the exercise, and the line of pull must be perpendicular to your torso.'),
           ('barbell-underhand-grip-bent-over-row', 3, 'Keep your back and neck neutral.'),
           ('barbell-underhand-grip-bent-over-row', 4, 'Your grip should be shoulder-width apart and your elbows should be close to your body.'),
           ('barbell-underhand-grip-bent-over-row', 5, 'Keep your body still throughout the exercise. Only your arms should move. Do not swing or use momentum to lift the barbell.'),
           ('barbell-underhand-grip-bent-over-row', 6, 'See also the bent-over barbell row and the underhand Yates row.'),

           ('one-arm-knee-push-up', 1, 'The one-arm knee push-up is a compound unilateral exercise that’s great for building your pectoralis major and triceps brachii. It will also challenge your core.'),
           ('one-arm-knee-push-up', 2, 'For the safety of your shoulder joints, keep your elbow tucked in slightly.'),
           ('one-arm-knee-push-up', 3, 'Place your knees wide apart and engage your core muscles for stability.'),
           ('one-arm-knee-push-up', 4, 'Perform the one-arm knee push-up with your weaker arm first. Follow with your stronger arm, but do not perform more repetitions than you did with your weaker arm. This will allow your weaker arm to catch up in strength with your stronger arm.'),
           ('one-arm-knee-push-up', 5, 'To put your body out of balance even more and force the recruitment of even more stabilizer muscles in your core, you can raise your arm out to your side instead of putting it behind your back.'),

           ('incline-dumbbell-hammer-curl', 1, 'Targeting the brachioradialis, the incline dumbbell hammer curl is great for strengthening and building the elbow flexors.'),
           ('incline-dumbbell-hammer-curl', 2, 'The inclined seated position stretches the long head of the biceps brachii, allowing it to make more of a contribution to elbow flexion than the short head does. However, the brachioradialis is still the target muscle since the hammer (neutral) grip is used. Thus, the biceps brachii and brachialis only act as synergists in this exercise.'),
           ('incline-dumbbell-hammer-curl', 3, 'Only your forearms should move. Keep the rest of your body still.'),
           ('incline-dumbbell-hammer-curl', 4, 'Be sure to use a hammer (neutral) grip throughout the exercise. Supinating your forearm as you flex your elbow, as you would with the incline dumbbell curl, will emphasize your biceps brachii, making it the target muscle instead of your brachioradialis.'),
           ('incline-dumbbell-hammer-curl', 5, 'See also the dumbbell hammer curl and the dumbbell cross-body hammer curl.'),

           ('standing-dumbbell-kickback', 1, 'Keep your back neutral and your right elbow tucked into the side of your torso as you extend your right elbow.'),
           ('standing-dumbbell-kickback', 2, 'Keep your body and upper arms still throughout the exercise so that your triceps brachii is effectively isolated and targeted. Only your forearms should be moving throughout the exercise.'),
           ('standing-dumbbell-kickback', 3, 'Do not arch or hunch your back.'),
           ('standing-dumbbell-kickback', 4, 'Raise your elbow higher than your shoulder for a greater range of motion.'),
           ('standing-dumbbell-kickback', 5, 'Perform the standing dumbbell kickback on your weaker arm first. With your stronger arm, do not perform more repetitions than your weaker arm. This promotes equal strength between your arms.'),
           ('standing-dumbbell-kickback', 6, 'If your elbows drop down as you straighten them, the dumbbells are too heavy. Consider using lighter dumbbells so that you can perform the exercise with proper form.'),

           ('incline-dumbbell-curl', 1, 'Keep your upper arms fixed. Only your forearms should move.'),
           ('incline-dumbbell-curl', 2, 'Make sure you fully supinate your forearms.'),
           ('incline-dumbbell-curl', 3, 'When a muscle is stretched, it can contract with more force. In the starting position of the incline dumbbell curl, the long head of your biceps brachii is more stretched than the short head. As a result, it gets more involved in the lift.'),
           ('incline-dumbbell-curl', 4, 'Since the majority of your biceps’ peak is made up by the long head, the incline dumbbell curl is great for building a bigger biceps peak.'),
           ('incline-dumbbell-curl', 5, 'Instead of alternating your arms during the incline dumbbell curl, you can complete all of the repetitions for one arm before performing the repetitions for the opposite arm. In order to promote the development of equal strength, start with your weaker arm, and never perform more repetitions with your stronger arm.'),
           ('incline-dumbbell-curl', 6, 'See also the incline dumbbell inner-biceps curl.'),

           ('incline-dumbbell-inner-biceps-curl', 1, 'Use the incline dumbbell inner-biceps curl to develop the inner/short head of the biceps brachii, which gives the biceps brachii width.'),
           ('incline-dumbbell-inner-biceps-curl', 2, 'Sitting in an inclined position, turning the palms away from the body and externally rotating the shoulders stretches the inner/short head of the biceps brachii, forcing it to contribute more to the exercise than the outer/long head of the biceps brachii. However, the brachialis is the target muscle in this exercise.'),
           ('incline-dumbbell-inner-biceps-curl', 3, 'Only your forearms should move.'),
           ('incline-dumbbell-inner-biceps-curl', 4, 'Instead of performing the dumbbell curl with both arms simultaneously, you can alternate curling the dumbbell up per repetition. You can also perform all repetitions on one arm first, followed by the opposite side.'),
           ('incline-dumbbell-inner-biceps-curl', 5, 'See also the incline dumbbell curl.'),

           ('decline-dumbbell-triceps-extension', 1, 'Keep your upper arms fixed. Only your forearms should move.'),
           ('decline-dumbbell-triceps-extension', 2, 'At the top of the movement, do not lock out your elbows.'),

           ('cable-rear-drive', 1, 'Keep your body still. Only your arm should move.'),
           ('cable-rear-drive', 2, 'Keep your upper arm horizontal. If your elbow drops, your latissimus dorsi will get involved.'),
           ('cable-rear-drive', 3, 'Adjust the way you stand to ensure resistance throughout the full range of motion.'),
           ('cable-rear-drive', 4, 'The cable rear drive is a rare exercise that combines a pulling movement (when you pull your elbow out to the side, more properly known as horizontally shoulder extension) and a pushing movement (when you extend your elbow). It’s a kind of rear delt row to horizontal triceps extension.'),
           ('cable-rear-drive', 5, 'When you go heavy with the cable rear drive, numerous muscles in your legs and core are significantly activated to stabilize your body.'),

           ('seated-dumbbell-wrist-curl', 1, 'Keep your back straight.'),
           ('seated-dumbbell-wrist-curl', 2, 'Keep your wrists and elbows at approximately the same height. This will ensure that you experience resistance throughout the full range of motion.'),
           ('seated-dumbbell-wrist-curl', 3, 'Instead of placing your forearms on your knees, you can place them on a flat bench so that your wrists extend off the side.'),
           ('seated-dumbbell-wrist-curl', 4, 'Use the seated dumbbell wrist curl to build your forearms and improve your grip strength. Note, however, that heavy wrist curling exercises can have a high injury risk because your wrists aren’t designed to curl heavy weights. Therefore, I always recommend the farmer’s walk, hand grippers, and static pull-up bar holds for building forearms and improving grip strength.'),
           ('seated-dumbbell-wrist-curl', 5, 'Because they wear out your grip strength, use forearm exercises such as the seated dumbbell wrist curl at the end of your workouts.'),

           ('close-grip-barbell-bench-press', 1, 'Using a shoulder-width grip and tucking your elbows into your body are important to maximize the emphasis on your triceps brachii instead of on your pectoralis major.'),
           ('close-grip-barbell-bench-press', 2, 'Do not use a grip that’s narrower than shoulder width. This will not put more emphasis on your triceps brachii. Instead, it will decrease your range of motion, put excessive pressure on your wrists, and limit the amount of weight that you can use.'),
           ('close-grip-barbell-bench-press', 3, 'Never use a false (aka thumbless or “suicide”) grip with any kind of bench press, including the close-grip barbell bench press.'),
           ('close-grip-barbell-bench-press', 4, 'For safety, have a spotter ready when lifting heavy.'),
           ('close-grip-barbell-bench-press', 5, 'When performed using proper form, the close-grip barbell bench press is one of the most effective exercises for activation and development of the triceps brachii.'),
           ('close-grip-barbell-bench-press', 6, 'See also the diamond push-up.'),

           ('standing-dumbbell-preacher-curl', 1, 'Keep the back of your upper arm, from your armpit to your elbow, flat on the bench.'),
           ('standing-dumbbell-preacher-curl', 2, 'Do not allow the dumbbell to touch the bench.'),
           ('standing-dumbbell-preacher-curl', 3, 'The standing dumbbell preacher curl targets your brachialis, not your biceps brachii. The brachialis is the strongest flexor of your elbow. Part of it sits under your biceps brachii, while the rest sits on the side of your upper arm, between your biceps brachii and triceps brachii. As such, when you build your brachialis, you produce a bigger biceps peak (because the brachialis props up your biceps) and you increase the separation between your biceps brachii and triceps brachii.'),

           ('seated-dumbbell-overhead-triceps-extension', 1, 'When you have finished, bring the dumbbell around your back and rest the lower end on your shoulder. Grab the bar securely with both hands, one on top of the other, raise your knee, and gently bring the other end of the dumbbell down onto your knee.'),
           ('seated-dumbbell-overhead-triceps-extension', 2, 'When performing the seated dumbbell overhead triceps extension, keep your elbows close to your head. This will keep the emphasis on your triceps brachii. If you have to open up your elbows (move them away from your head) to raise the dumbbell, it means that the dumbbell is too heavy.'),
           ('seated-dumbbell-overhead-triceps-extension', 3, 'Your upper arms must be kept vertical. If your shoulder flexibility does not permit this, sit with your hips forward and rest your back on a chair.'),
           ('seated-dumbbell-overhead-triceps-extension', 4, 'Try not to raise the dumbbell directly over your head, as this can be dangerous. Tilt your head forward a little, and raise and lower the dumbbell behind your back.'),
           ('seated-dumbbell-overhead-triceps-extension', 5, 'The point of sitting down is to reduce your ability to cheat by using body momentum to raise the dumbbell.'),
           ('seated-dumbbell-overhead-triceps-extension', 6, 'See also the overhead barbell triceps extension and the seated two-arm overhead dumbbell triceps extension.'),

           ('dumbbell-reverse-curl', 1, 'Keep your body still and your upper arms by your sides.'),
           ('dumbbell-reverse-curl', 2, 'Keep your wrists straight.'),
           ('dumbbell-reverse-curl', 3, 'Maintain a shoulder-width reverse grip.'),
           ('dumbbell-reverse-curl', 4, 'Instead of curling both arms at the same time, you can, of course, alternate your arms.'),
           ('dumbbell-reverse-curl', 5, 'Using the reverse grip puts your biceps brachii into a mechanically disadvantaged position, which forces your other forearm flexors (i.e. your brachialis and brachioradialis, especially the latter) to work harder.'),
           ('dumbbell-reverse-curl', 6, 'See also the EZ bar reverse curl.'),

           ('ez-bar-reverse-curl', 1, 'Keep your body rigid and your elbows against your sides. Only your forearms should move.'),
           ('ez-bar-reverse-curl', 2, 'Unlike what most people think, the EZ bar reverse curl targets your brachioradialis, not your biceps brachii. The reason is that holding the bar using a pronated grip puts the biceps brachii into a position of mechanical disadvantage, which forces the brachialis and especially the brachioradialis to work harder.'),
           ('ez-bar-reverse-curl', 3, 'The EZ bar reverse curl is great for building both your forearms and upper arms.'),
           ('ez-bar-reverse-curl', 4, 'See also the barbell and dumbbell reverse curls.'),

           ('arnold-press', 1, 'Keep your back straight and body still.'),
           ('arnold-press', 2, 'The Arnold press was invented by the Terminator himself, Arnold Schwarzenegger.'),
           ('arnold-press', 3, 'Once you get the hang of the Arnold press as described above, try the following: Allow your arms to move out as they ascend and then move back in at the top of the movement. This combines the movements of the lateral raise and shoulder press to produce a fluid motion that minimizes the amount of twisting you have to do with your wrists and keeps all of the movement in your shoulders.'),

           ('dumbbell-lateral-raise', 1, 'Keep a natural curvature of the spine.'),
           ('dumbbell-lateral-raise', 2, 'Keep your body still; only your arms should move.'),
           ('dumbbell-lateral-raise', 3, 'Do not swing the dumbbells or let them drop down by your sides.'),
           ('dumbbell-lateral-raise', 4, 'Use the dumbbell lateral raise to strengthen and build your anterior and lateral deltoids, which will give you broad shoulders.'),
           ('dumbbell-lateral-raise', 5, 'Perform the dumbbell lateral raise one arm at a time to get more stabilizer muscles in your core involved and help you to develop unilateral upper-body strength.'),
           ('dumbbell-lateral-raise', 6, 'See also the leaning dumbbell lateral raise.'),

           ('bent-over-lateral-raise', 1, 'Do not swing the dumbbells upward.'),
           ('bent-over-lateral-raise', 2, 'Try to resist the lowering of the dumbbells.'),
           ('bent-over-lateral-raise', 3, 'Keep your back straight and your body still.'),
           ('bent-over-lateral-raise', 4, 'You will not target your posterior deltoids unless your torso is horizontal and your upper arms are perpendicular to your torso.'),
           ('bent-over-lateral-raise', 5, 'The reverse dumbbell fly is also known as the dumbbell rear lateral raise, the dumbbell rear delt fly, and the dumbbell bent-over lateral raise.'),
           ('bent-over-lateral-raise', 6, 'Also see the seated reverse dumbbell fly and the head-supported reverse dumbbell fly.'),

           ('cable-external-shoulder-rotation', 1, 'Keep your elbow locked to your side and bent at a 90-degree angle.'),
           ('cable-external-shoulder-rotation', 2, 'Place a towel under your elbow. If it drops, it means that you are not keeping your elbow locked to your side.'),
           ('cable-external-shoulder-rotation', 3, 'The cable external shoulder rotation exercise has been included in the training programs to promote shoulder health, which makes it very important'),
           ('cable-external-shoulder-rotation', 4, 'If you don’t have access to a cable machine, lie on your side and use a dumbbell instead. See the dumbbell lying external shoulder rotation.'),

           ('cable-one-arm-lateral-raise', 1, 'Keep your torso still, your back straight, and your elbow slightly bent.'),
           ('cable-one-arm-lateral-raise', 2, 'Try to resist the lowering phase of the repetition.'),
           ('cable-one-arm-lateral-raise', 3, 'Placing your free hand on your hip instead of holding on to something for support forces the recruitment of more muscles for stabilization.'),
           ('cable-one-arm-lateral-raise', 4, 'As with all unilateral exercises, start the cable one-arm lateral raise with your weak side, and never do more repetitions with your strong side. This will promote the development of equal strength on both sides.'),

           ('seated-dumbbell-lateral-raise', 1, 'Keep your back straight, your shoulders back, and your elbows slightly bent. Most people bend their elbows way too much.'),
           ('seated-dumbbell-lateral-raise', 2, 'Make sure that your upper arms rise directly upward and descent directly downward.'),
           ('seated-dumbbell-lateral-raise', 3, 'Most instructors recommend that you internally rotate your shoulders so that your elbows are higher than your wrists and it looks like you are pouring a jug of water when you raise your arm. This better targets your lateral deltoid. However, it also increases the risk of shoulder impingement! You can reduce the risk of shoulder impingement and still better target your lateral deltoid by externally rotating your shoulders and leaning forward a little'),
           ('seated-dumbbell-lateral-raise', 4, 'The dumbbell lateral raise can of course also be performed while standing. The difference is that the seated dumbbell lateral raise minimizes your ability to cheat.'),

           ('plate-front-raise', 1, 'Keep your body still. Don’t sway back and forth as you raise and lower the weight plate.'),
           ('plate-front-raise', 2, 'You can reduce your potential to cheat during the plate front raise by sitting down and lowering the plate to between your legs.'),
           ('plate-front-raise', 3, 'If you lift heavy, the weight plate front raise will significantly challenge your core and especially your lower back. Therefore, increase weight gradually to give your lower back time to adapt.'),
           ('plate-front-raise', 4, 'Keeping a slight bend in your knees can help to decrease the pressure on your lower back.'),
           ('plate-front-raise', 5, 'See also the alternating dumbbell front raise.'),

           ('dumbbell-one-arm-upright-row', 1, 'Do not pull the dumbbell up any higher than shoulder level in an internally rotated position, as this can cause your tendon to get impinged (pinched) by your shoulder bones.'),
           ('dumbbell-one-arm-upright-row', 2, 'To reduce your risk for shoulder injury, avoid very heavy weights and warm up thoroughly before performing the dumbbell one-arm upright row.'),
           ('dumbbell-one-arm-upright-row', 3, 'Keep your body upright, shoulders back, and chest out.'),
           ('dumbbell-one-arm-upright-row', 4, 'Pull with your elbows, not your biceps.'),

           ('seated-dumbbell-one-arm-shoulder-press', 1, 'The seated dumbbell one-arm shoulder press is brilliant for developing unilateral upper-body strength. Sitting down allows you to better isolate your shoulders since it takes your legs out of the equation, reducing your potential to cheat.'),
           ('seated-dumbbell-one-arm-shoulder-press', 2, 'Since you are only using one arm, the seated dumbbell one-arm shoulder press also forces the recruitment of stabilizer muscles in the core.'),
           ('seated-dumbbell-one-arm-shoulder-press', 3, 'Engage your core and keep your head facing forward; don’t look up.'),
           ('seated-dumbbell-one-arm-shoulder-press', 4, 'When pressing the dumbbell upward, you may lean a little to the opposite side. Otherwise, keep your torso upright.'),
           ('seated-dumbbell-one-arm-shoulder-press', 5, 'Do not lock your elbow out at the top of the press.'),
           ('seated-dumbbell-one-arm-shoulder-press', 6, 'In vertical pushing exercises, the anterior deltoid is always targeted. However, the involvement of other upper-body muscles will depend on the position of the elbow. Having your elbow directly to the side will combine shoulder abduction and elbow extension, keeping your upper pectoralis major and the short head of your biceps brachii from being synergistically activated. This allows you to further isolate your shoulder muscles, specifically the anterior deltoid.'),

           ('one-arm-dumbbell-bent-over-lateral-raise', 1, 'Keep your back straight and your body still; only your arm should move.'),
           ('one-arm-dumbbell-bent-over-lateral-raise', 2, 'Keep the movement under full control. Do not swing the dumbbell upward or allow it to drop downward.'),
           ('one-arm-dumbbell-bent-over-lateral-raise', 3, 'The point of holding on to something stable is to make sure that your body stays still and doesn’t sway up and down. In other words, it prevents you from cheating.'),
           ('one-arm-dumbbell-bent-over-lateral-raise', 4, 'The more upright your torso is, the more emphasis you will place on your lateral deltoid instead of your posterior deltoid. Therefore, in order to target your posterior deltoid, keep your torso horizontal.'),
           ('one-arm-dumbbell-bent-over-lateral-raise', 5, 'To avoid the involvement of your latissimus dorsi, keep your upper arm perpendicular to your torso.'),
           ('one-arm-dumbbell-bent-over-lateral-raise', 6, 'The one-arm reverse dumbbell fly is also known as the one-arm dumbbell rear delt fly, the one-arm dumbbell rear lateral raise and the one-arm dumbbell bent-over lateral raise.'),

           ('triceps-dip', 1, 'Do not lock out your elbows at the top of the movement.'),
           ('triceps-dip', 2, 'Keep your body upright and elbows tucked in. If you lean forward and flare out your elbows, you will place more emphasis on your lower pectoralis major, and the exercise will become a chest dip instead of a triceps dip.'),
           ('triceps-dip', 3, 'Make the triceps dip more difficult by holding a dumbbell between your legs or wearing a weighted dip belt (weighted triceps dip).'),
           ('triceps-dip', 4, 'Make it easier by using an assisted dip machine, or by bending your knees and getting someone to hold your legs.'),
           ('triceps-dip', 5, 'n a study by the American Council on Exercise (ACE), the bench dip, which is very similar to the triceps dip, was found to be the third most effective triceps exercise after the triangle push-up (aka diamond push-up, which came first) and the dumbbell kickback (which came second).'),

           ('bench-press', 1, 'Planting your feet, arching your back, tucking in your elbows, and straightening your wrists allow you to drive from your legs, through your body, and up through your arms—thus getting your entire body behind the press. Use this form to produce a strong foundation from which to press, increase your leverage, and give yourself a mechanical advantage.'),
           ('bench-press', 2, 'Tucking in your elbows also reduces the pressure on your shoulders.'),
           ('bench-press', 3, 'Never use a false grip. A false grip (aka thumbless or suicide grip) is when you don’t wrap your thumbs around the bar.'),
           ('bench-press', 4, 'If lifting heavy weights, have a spotter ready.'),
           ('bench-press', 5, 'Like the barbell squat and barbell deadlift, the barbell bench press is a major mass- and strength-building exercise.'),
           ('bench-press', 6, 'Also see the dumbbell bench press.'),

           ('cable-cross-over', 1, 'Maintain control of the cables at all times.'),
           ('cable-cross-over', 2, 'Keep your body still, your back straight, and your elbows slightly bent.'),
           ('cable-cross-over', 3, 'It’s a good idea to cross the handles at the top of the movement and thus strengthen the fly range of motion, which you can’t strengthen with exercises such as the barbell bench press and the dumbbell fly.'),
           ('cable-cross-over', 4, 'The standing cable fly and the dumbbell fly are similar exercises, targeting the same muscles. One way in which the standing cable fly is better than the dumbbell fly is that, with the dumbbell fly, the resistance placed on the pectoralis major is reduced at the top of the movement, when the dumbbells are held over the chest. With the standing cable fly, resistance on the pectoralis major is maintained throughout the movement.'),
           ('cable-cross-over', 5, 'Another way in which the standing cable fly beats the dumbbell fly is that it helps you to develop your standing balance, coordination, and push force, which are important for fitness and athleticism. The standing cable fly also recruits more stabilizer muscles, especially in your core.'),

           ('low-cable-cross-over', 1, 'Keep your body still; only your arms should move.'),
           ('low-cable-cross-over', 2, 'Keep your elbows slightly bent.'),
           ('low-cable-cross-over', 3, 'Maintain full control of the cables at all times. Do not let the weight stack drop when your lower it.'),
           ('low-cable-cross-over', 4, 'As with the standing cable fly, the standing incline cable fly helps you to develop your standing push force, balance, and coordination—all of which are important for athleticism and sporting performance.'),
           ('low-cable-cross-over', 5, 'Compared with many other chest exercises, the standing cable fly exercises also recruit more stabilizer muscles, especially in your core.'),

           ('decline-barbell-bench-press', 1, 'Never use a thumbless grip (aka suicide grip)!'),
           ('decline-barbell-bench-press', 2, 'Do not lock your elbows out at the top of the press.'),
           ('decline-barbell-bench-press', 3, 'If lifting heavy, have a spotter ready.'),
           ('decline-barbell-bench-press', 4, 'Retracting your shoulder blades, keeping your elbows tucked in a little, and keeping your wrists straight help you to drive the barbell upward.'),
           ('decline-barbell-bench-press', 5, 'Keeping your elbows tucked in also reduces the pressure on your shoulders, which are prone to injury.'),
           ('decline-barbell-bench-press', 6, 'Compared with the standard barbell bench press, many lifters can lift more weight with the decline barbell bench press. The exercise also often feels easier on the shoulders.'),

           ('incline-barbell-bench-press', 1, 'Planting your feet firmly on the floor, arching your back, retracting your shoulder blades, tucking in your elbows, and straightening your wrists allow you to produce a strong foundation from which to press and get your whole body behind the lift.'),
           ('incline-barbell-bench-press', 2, 'Tucking in your elbows also reduces the pressure on your shoulders, which are prone to injury with this and other pressing exercises.'),
           ('incline-barbell-bench-press', 3, 'An angle of 45 degrees is recommended because, when compared with other angles (0, 28, and 56), the clavicular head of the pectoralis major was found to be most active at 44 degrees, and 45 degrees is the closest setting.'),
           ('incline-barbell-bench-press', 4, 'Never use a false (aka thumbless or “suicide”) grip with the incline barbell bench press. Hold the bar deep in your palms and wrap your thumbs securely around the bar.'),
           ('incline-barbell-bench-press', 5, 'Don’t go as heavy as you would with the flat barbell bench press.'),
           ('incline-barbell-bench-press', 6, 'The incline barbell bench press is probably the most popular exercise for targeting your upper chest. However, the incline reverse-grip barbell bench press may be more effective.'),

           ('incline-dumbbell-bench-press', 1, 'Use a bench inclination of 45 degrees because, when compared with other angles (0, 28, and 56), the clavicular head of the pectoralis major was found to be most active at 44 degrees, and 45 degrees is the closest setting.'),
           ('incline-dumbbell-bench-press', 2, 'Planting your feet, tucking in your elbows a little, and straightening your wrists allow you to drive from your legs, through your body, and up through your arms, thus getting your entire body behind the press.'),
           ('incline-dumbbell-bench-press', 3, 'Tucking your elbows in a little also reduces the pressure on your shoulders.'),
           ('incline-dumbbell-bench-press', 4, 'Try not to drop the dumbbells on the floor, by your sides, after you have finished. Instead, raise your knees and carefully bring the dumbbells down onto them. The weight of the dumbbells will then push your legs down and help you to sit up.'),
           ('incline-dumbbell-bench-press', 5, 'You can perform the incline dumbbell bench press unilaterally (one arm at a time), which will force the recruitment of more core stabilizer muscles and help you to develop unilateral strength. In order to enjoy the benefits of both unilateral and bilateral training, alternate between the two variations.'),

           ('dumbbell-fly', 1, 'Keep your elbows slightly bent.'),
           ('dumbbell-fly', 2, 'Keep the movement slow and deliberate.'),
           ('dumbbell-fly', 3, 'There’s no need to bring the dumbbells together at the top of the movement because once they are vertical, there is almost no resistance to work against.'),
           ('dumbbell-fly', 4, 'Arching your back and sticking out your chest will reduce the pressure on your shoulders and focus it on your chest.'),
           ('dumbbell-fly', 5, 'Internally rotating your shoulders (so that your elbows point out to the sides) better isolates your pectoralis major because it brings the origin and insertion of the muscle into better alignment.'),
           ('dumbbell-fly', 6, 'Since you can’t go heavy with the dumbbell fly (because doing so is dangerous), the exercise is not a mass builder. As an isolation exercise, it is useful if you want to warm up your chest, pre-exhaust it before the compound chest exercises, or flush it at the end of a chest workout.'),
           ('dumbbell-fly', 7, 'The dumbbell fly doesn’t target your inner chest. This is a popular myth. Isolation of your inner chest is impossible. The only ways to produce more inner chest definition are to build your chest using compound exercises and to reduce your body fat.'),
           ('dumbbell-fly', 8, 'Another popular myth is that the dumbbell fly stretches your pecs to give you a broader chest. It doesn’t. See the second video.'),
           ('dumbbell-fly', 9, 'Instead of the dumbbell fly, I usually recommend the cable cross-over for reasons explained on the cable cross-over page.'),

           ('machine-fly', 1, 'Adjust the fly machine for comfort and proper back support.'),
           ('machine-fly', 2, 'Keep the movement slow and deliberate.'),
           ('machine-fly', 3, 'By internally rotating your shoulders (so that your wrists, elbows, and shoulders are level), you better isolate your pectoralis major because the origin and insertion of the muscle are brought more into line.'),
           ('machine-fly', 4, 'The machine fly is not a major mass-building exercise. As an isolation exercise, it is useful if you want to warm up your chest, pre-exhaust it before the compound chest exercises, or flush it at the end of a chest workout.'),
           ('machine-fly', 5, 'The machine fly doesn’t target your inner chest. This is a myth. It is not possible to emphasize your inner chest. The only ways to produce more inner chest definition are to reduce your body fat level and keep building your chest using compound exercises.'),
           ('machine-fly', 6, 'Another popular myth regarding the machine fly is that it stretches your pecs to give you a broader chest.'),

           ('svend-press', 1, 'Since your arms are horizontal, most of the movement should occur in the horizontal plane.'),
           ('svend-press', 2, 'Because you have to constantly squeeze the plate, the Svend press puts your chest through an extended period of tension.'),
           ('svend-press', 3, 'Instead of using one heavy plate, you can sandwich two lighter plates together.'),
           ('svend-press', 4, 'The Svend press is not a major mass-building exercise. You can use it to warm up your chest at the start of a chest workout or to flush your chest at the end of your chest workout. You can also superset the Svend press with a primary chest exercise, such as the dumbbell bench press. In other words, as soon as you complete a set of the dumbbell bench press, perform the Svend press.'),
           ('svend-press', 5, 'As with the dumbbell fly, the Svend press is believed to build your “inner” chest. It is not possible to emphasize your inner chest. The only ways to get more inner chest definition are to build your chest using major compound push exercises (such as the barbell bench press) and to lose body fat.'),
           ('svend-press', 6, 'A similar exercise to the Svend press, known as the dumbbell squeeze bench press, can be performed while lying on your back (supine). The dumbbell squeeze bench press places emphasis on your pectoralis major and triceps brachii, whereas the Svend press places emphasis on your pectoralis major and anterior deltoid.'),

           ('isometric-wiper', 1, 'The isometric wiper is not a mass-building exercise. Use it either to warm up your chest at the start of a chest workout or to burn it out at the end of a chest workout.'),
           ('isometric-wiper', 2, 'Your pectoralis major and anterior deltoid are mainly exercised isometrically, whereas your triceps brachii is exercised dynamically.'),
           ('isometric-wiper', 3, 'Your elbow flexors (biceps brachii, brachialis, and brachioradialis) get involved to a significant degree only if you position your hands out very wide.'),
           ('isometric-wiper', 4, 'If you perform the isometric wiper with a very wide hand position, point your fingers out to the sides to reduce the pressure on your wrists.'),

           ('hammer-grip-dumbbell-bench-press', 1, 'When you have finished, do not drop the dumbbells to your sides. Instead, carefully lower the dumbbells towards your thighs and allow the weight of the dumbbells to help you to sit up.'),
           ('hammer-grip-dumbbell-bench-press', 2, 'The hammer-grip dumbbell bench press places less stress on your shoulder joints than does the standard dumbbell bench press. As such, the hammer-grip dumbbell bench press is more suitable for those who suffer from shoulder pain. However, the standard dumbbell bench press, in which you of course use a pronated (overhand) grip, is arguably slightly better at activating the pectoralis major because it usually involves more internal shoulder rotation.'),
           ('hammer-grip-dumbbell-bench-press', 3, 'No matter what kind of grip you use, to reduce the pressure on your shoulder joints, always keep your elbows tucked in to your torso at 45-degree angles.'),

           ('decline-dumbbell-fly', 1, 'To preserve your elbow joints, keep your elbows slightly flexed.'),
           ('decline-dumbbell-fly', 2, 'Keep the movement slow and controlled.'),
           ('decline-dumbbell-fly', 3, 'The reason for internally rotating your shoulders is to better isolate your sternal pectoralis major by bringing the muscle’s origin and insertion into better alignment.'),
           ('decline-dumbbell-fly', 4, 'The steeper the angle of the bench, the less your anterior deltoid will contribute as a synergist.'),
           ('decline-dumbbell-fly', 5, 'Use the decline dumbbell fly to warm up, pre-exhaust, or burn out your sternal pectoralis major. It is not a major mass-building exercise.'),

           ('decline-dumbbell-bench-press', 1, 'When you have finished the decline dumbbell bench press, gently rest the dumbbells on your thighs and sit up. Do not drop the dumbbells by your sides.'),
           ('decline-dumbbell-bench-press', 2, 'To reduce the pressure on your shoulder joints and thus promote shoulder health, keep your elbows tucked into your body a little.'),
           ('decline-dumbbell-bench-press', 3, 'Compared with the dumbbell bench press, the decline dumbbell bench press places a little more emphasis on your sternal pectoralis major.'),
           ('decline-dumbbell-bench-press', 4, 'You can perform the decline dumbbell press on the floor with very little loss of range of motion.'),
           ('decline-dumbbell-bench-press', 5, 'See also the decline hammer-grip dumbbell bench press, which can be easier on your shoulder joints.'),

           ('incline-dumbbell-fly', 1, 'Keep your elbows slightly flexed.'),
           ('incline-dumbbell-fly', 2, 'Internally rotating your shoulders will serve to better isolate your pectoralis major because the origin and insertion of the muscle are brought into better alignment.'),
           ('incline-dumbbell-fly', 3, 'When you have finished, bring your knees up and gently lower the dumbbells down onto your knees, which will help you to sit up.'),
           ('incline-dumbbell-fly', 4, 'Do not go very heavy with the incline dumbbell fly or any other type of fly exercise because doing so can be dangerous.'),
           ('incline-dumbbell-fly', 5, 'See also the incline cable fly and the dumbbell fly.'),

           ('barbell-jm-press', 1, 'Keep your elbows high and approximately 45 degrees out to your sides. Keeping your elbows high will emphasize elbow extension over horizontal shoulder flexion and therefore emphasize the involvement of your triceps brachii while minimizing the involvement of your pectoralis major and anterior deltoid.'),
           ('barbell-jm-press', 2, 'This exercise requires practice. Start light and increase weight as you master proper form.'),
           ('barbell-jm-press', 3, 'After you master form, start to push the barbell upward more rapidly to develop greater triceps power.'),
           ('barbell-jm-press', 4, 'The barbell JM press is a cross between a barbell skull crusher and a barbell bench press. It was invented by powerlifter JohnMark ‘JM’ Blakly.'),
           ('barbell-jm-press', 5, 'Also known as the barbell Blakly press.'),

           ('incline-dumbbell-press-on-a-stability-ball', 1, 'The purpose of using a stability ball instead of an inclined bench is to add instability to the exercise, which forces the recruitment of many stabilizer muscles, especially in your core.'),
           ('incline-dumbbell-press-on-a-stability-ball', 2, 'For balance, keep your feet spread out and firmly planted on the floor.'),
           ('incline-dumbbell-press-on-a-stability-ball', 3, 'Keeping your elbows tucked in a little helps to reduce the pressure on your shoulder joints.'),
           ('incline-dumbbell-press-on-a-stability-ball', 4, 'Be sure that you have first mastered the standard incline dumbbell bench press before attempting the incline dumbbell press on a stability ball.'),

           ('dumbbell-press-on-a-stability-ball', 1, 'The dumbbell press on a stability ball activates more stabilizer muscles than does the dumbbell bench press. This is because the stability ball adds instability to the exercise, forcing more stabilizer muscles throughout the body, especially in the core, to be recruited.'),
           ('dumbbell-press-on-a-stability-ball', 2, 'To reduce instability and make the exercise easier, spread out your feet.'),
           ('dumbbell-press-on-a-stability-ball', 3, 'The point of keeping your elbows slightly tucked in to you body is to reduce pressure on your shoulder joints.'),
           ('dumbbell-press-on-a-stability-ball', 4, 'Getting into the right position on the stability ball and getting back up after completing the exercise can be challenging when holding heavy dumbbells. Therefore, it’s wise to practice the exercise with lighter dumbbells before going heavy.'),
           ('dumbbell-press-on-a-stability-ball', 5, 'See also the incline dumbbell press on a stability ball.'),

           ('barbell-deadlift', 1, 'Keep your arms and back straight, your torso upright, and your feet and knees pointing in the same direction.'),
           ('barbell-deadlift', 2, 'At the top of the lift, do not hyperextend your back.'),
           ('barbell-deadlift', 3, 'Keep the barbell close to your body to improve mechanical leverage.'),
           ('barbell-deadlift', 4, 'You can use gym chalk or wrist straps to improve your grip.'),
           ('barbell-deadlift', 5, 'Start light and add weight gradually to give your lower back time to adapt.'),
           ('barbell-deadlift', 6, 'When lifting heavy, you can wear a support belt to protect your lower back.'),
           ('barbell-deadlift', 7, 'The barbell deadlift is arguably the king of all major mass-building exercises, challenged only by the barbell squat. It is great for shocking your body into releasing testosterone, strengthening your legs and core, and building body-wide strength and mass.'),
           ('barbell-deadlift', 8, 'For beginners, you can start with the kettlebell deadlift before proceeding to this exercise.'),

           ('dumbbell-pullover', 1, 'Keep your arms slightly bent throughout the movement.'),
           ('dumbbell-pullover', 2, 'Keep your hips lower than your shoulders.'),
           ('dumbbell-pullover', 3, 'Do not arch your back.'),
           ('dumbbell-pullover', 4, 'Do not lower the dumbbell too far down behind your head.'),

           ('bent-over-dumbbell-row', 1, 'Pull with your elbow, not with your biceps.'),
           ('bent-over-dumbbell-row', 2, 'Keep your torso near horizontal and your elbow tucked in.'),
           ('bent-over-dumbbell-row', 3, 'Do not rotate your torso as you pull the dumbbell upward.'),
           ('bent-over-dumbbell-row', 4, 'Many people think that the biceps acts as a synergist in rowing exercises such as the bent-over dumbbell row, when, in fact, it acts as a dynamic stabilizer, along with the long head of the triceps brachii.'),
           ('bent-over-dumbbell-row', 5, 'The bent-over dumbbell row is great for developing unilateral upper-body strength.'),
           ('bent-over-dumbbell-row', 6, 'As with all unilateral exercises (exercises that allow you to train one side of your body at a time), start with your weak side, and do not perform more reps with your strong side. This will allow your weak side to catch up.'),

           ('pull-up', 1, 'Pull with your elbows, not with your biceps.'),
           ('pull-up', 2, 'Avoid swinging.'),
           ('pull-up', 3, 'Make the exercise easier by bending your knees and getting someone to hold your feet. You can also use an assisted pull-up machine.'),
           ('pull-up', 4, 'Make the exercise more difficult by wearing a weighted vest or dip belt, by holding a dumbbell between your feet, or by trying some of the numerous advanced pull-up variations (see second video), such as the L-sit pull-up.'),
           ('pull-up', 5, 'The pull-up is a compound exercise that will help you to develop major functional upper-body strength and a wide tapering back. If doing lat pull-downs, your goal should be to graduate to pull-ups at some point.'),
           ('pull-up', 6, 'If you can’t do pull-ups, keep increasing the amount of weight that you pull down until it nears your own weight. Then, practice the negative pull-up (see third video), which will help you to develop the strength necessary to perform proper pull-ups.'),
           ('pull-up', 7, 'If you use a supinated (underhand) grip, it becomes a chin-up.'),

           ('dumbbell-shrug', 1, 'Keep your arms slightly bent.'),
           ('dumbbell-shrug', 2, 'Do not move your arms. Only your shoulders should move.'),
           ('dumbbell-shrug', 3, 'Do not roll your shoulders.'),
           ('dumbbell-shrug', 4, 'The dumbbell shrug is great for building the size and strength of your upper and middle trapezius, which will help you with many other key lifts and movements.'),
           ('dumbbell-shrug', 5, 'Bodybuilders from the golden era, such as Frank Zane, are said to have avoided building the upper trapezius because a big upper trapezius makes your shoulders look less broad.'),
           ('dumbbell-shrug', 6, 'See also the barbell shrug and the Smith machine shrug.'),

           ('inverted-row', 1, 'In a comparison by Canadian scientists of the inverted row, the bent-over barbell row, and the standing one-arm cable row, the inverted row was found to elicit the highest activation of the latissimus dorsi, upper-back, and hip extensors. The exercise was also found to place far less stress on your lower back, making it ideal for people who have back problems.'),
           ('inverted-row', 2, 'In the inverted row, your biceps brachii and the long heads of your triceps brachii act as stabilizers only, not as synergists.'),
           ('inverted-row', 3, 'To make the inverted row easier, either raise the bar higher or perform the exercise while sitting on your buttocks.'),
           ('inverted-row', 4, 'To make the exercise more difficult, either wrap a chain around your torso, wear a weighted vest, or elevate your legs so that they are almost level with the bar. If you elevate your legs, you can also safely place a weight plate on your abdomen.'),
           ('inverted-row', 5, 'You can perform the inverted row at home by lying under a chair, holding the chair’s sides, and pulling yourself up.'),
           ('inverted-row', 6, 'Also known as the body row, supine row, Australian pull-up, and fat-man pull-up.'),
           ('inverted-row', 7, 'See also the underhand-grip inverted row.'),

           ('bent-over-two-arm-dumbbell-row', 1, 'Keep your neck level and head up, and try to maintain a natural curvature of the spine.'),
           ('bent-over-two-arm-dumbbell-row', 2, 'Pull with your elbows, not with your biceps.'),
           ('bent-over-two-arm-dumbbell-row', 3, 'Keeping your torso horizontal (or close to horizontal) and your elbows tucked in will ensure that you activate the right muscles.'),
           ('bent-over-two-arm-dumbbell-row', 4, 'The bent-over two-arm dumbbell row is great for developing upper-body strength once you master form and are able to go heavy. However, start light to allow your lower back time to adapt.'),
           ('bent-over-two-arm-dumbbell-row', 5, 'If the bent-over two-arm dumbbell row is hard on your lower back, use the bent-over dumbbell row or the cable row.'),

           ('barbell-sumo-deadlift', 1, 'Keep your hips low, torso upright, back straight, and head up.'),
           ('barbell-sumo-deadlift', 2, 'Don’t allow your knees to cave inward as you lift. Push them out to the sides.'),
           ('barbell-sumo-deadlift', 3, 'Keep your feet flat on the floor, and your feet and knees pointing in the same direction.'),
           ('barbell-sumo-deadlift', 4, 'Keep the bar close to your body to improve mechanical leverage.'),
           ('barbell-sumo-deadlift', 5, 'Start light, and increase the weight gradually as you learn proper form.'),
           ('barbell-sumo-deadlift', 6, 'When lifting very heavy, take a deep breath and hold it just until you complete the lift. Exhale as soon as you’re standing. This will help to brace and support your core. (To learn proper breathing technique when lifting heavy, research the “Valsalva maneuver”.)'),
           ('barbell-sumo-deadlift', 7, 'To improve your grip when lifting heavy, use a mixed grip (one hand over, one hand under).'),
           ('barbell-sumo-deadlift', 8, 'The barbell sumo deadlift is a major compound exercise. It is essentially the barbell deadlift performed using a very wide (or sumo) stance. The wide stance lowers your center of gravity and allows you to keep your torso more upright.'),
           ('barbell-sumo-deadlift', 9, 'Compared with the barbell deadlift, the barbell sumo deadlift puts less emphasis on your lower back and hamstrings, making it easier for those who have lower back problems.'),

           ('bent-over-one-arm-cable-pull', 1, 'Pull with your elbow, not with your biceps.'),
           ('bent-over-one-arm-cable-pull', 2, 'Keep your body still. Only your arm should move.'),
           ('bent-over-one-arm-cable-pull', 3, 'Use the bent-over one-arm cable pull to develop unilateral upper-body strength. It’s also a great exercise with which to warm up your lats and find the mind–muscle connection at the start of a back workout.'),

           ('one-arm-lat-pull-down', 1, 'Keep your body still. Only your arm should move.'),
           ('one-arm-lat-pull-down', 2, 'Pull the stirrup down with your elbow, not with your biceps.'),
           ('one-arm-lat-pull-down', 3, 'Use the one-arm lat pull-down to build your back muscles, especially your lats, and to develop unilateral upper-body strength. The exercise is also great for warming up and finding the mind–lats muscle connection before a back workout.'),

           ('seated-twisting-cable-row', 1, 'Keep your elbow close to your body.'),
           ('seated-twisting-cable-row', 2, 'Do not twist your torso beyond feeling a mild stretch in your side.'),
           ('seated-twisting-cable-row', 3, 'Use the seated twisting cable row to develop unilateral upper-body strength.'),

           ('standing-twisting-cable-high-row', 1, 'The pulley should be positioned a little over head height.'),
           ('standing-twisting-cable-high-row', 2, 'Keep the rotation of your hips to a minimum so that most of the rotation occurs in your waist.'),
           ('standing-twisting-cable-high-row', 3, 'Do not rotate your waist beyond feeling a mild stretch in your side.'),
           ('standing-twisting-cable-high-row', 4, 'The standing twisting cable high row is a brilliant exercise with which to develop core strength and stability and unilateral upper-body strength.'),
           ('standing-twisting-cable-high-row', 5, 'Try the exercise using both the stance described above and the opposite stance (see video) to see which one you prefer. The opposite stance will activate slightly different muscles in your hips, gluteals, and thighs.'),
           ('standing-twisting-cable-high-row', 6, 'See also the seated twisting cable row.'),

           ('rope-lat-pull-down', 1, 'Keep your core tight and your body still. Only your arms should move.'),
           ('rope-lat-pull-down', 2, 'Do not lean backward. Pull the rope down vertically.'),
           ('rope-lat-pull-down', 3, 'Pull the rope with your elbows, not with your biceps.'),
           ('rope-lat-pull-down', 4, 'If the rope is too long, kneel or sit on the floor.'),
           ('rope-lat-pull-down', 5, 'The rope lat pull-down is great for strengthening and building your back and arms, as well as for developing upper-body strength.'),
           ('rope-lat-pull-down', 6, 'Few people use the rope for lat pull-downs. It’s good to use different attachments sometimes, such as the rope, because different fibers are activated, which keeps your muscles challenged.'),
           ('rope-lat-pull-down', 7, 'Do not confused the rope lat pull-down with the triceps rope push-down.'),

           ('standing-cable-row', 1, 'Pull with your elbows, not with your biceps.'),
           ('standing-cable-row', 2, 'You can either keep your back straight and vertical, as in the illustration, or allow your back to flex and extend. In the former case, your spinal erectors (erector spinae) act as stabilizers, whereas in the latter case, they act as synergists.'),
           ('standing-cable-row', 3, 'Compared with the seated cable row, the standing cable row stimulates the recruitment of many more stabilizer muscles in your legs and core, especially when lifting heavy. However, if you want to lift very heavy, or if you want to emphasize your back muscles, use the seated cable row.'),
           ('standing-cable-row', 4, 'See also the straight-back seated cable row.'),

           ('barbell-good-morning', 1, 'When performing the barbell good morning, you should only feel a mild stretch in your hamstrings. Do not flex your hips beyond this point.'),
           ('barbell-good-morning', 2, 'Your range of motion will depend on the flexibility of your hamstrings. The less flexible your hamstrings are, the more you will need to flex your knees to lower your torso to your desired level.'),
           ('barbell-good-morning', 3, 'Keep your back and neck neutral throughout the exercise.'),
           ('barbell-good-morning', 4, 'Your erector spinae will be exercised isometrically, which means that it will contract but it will be held at a fixed length. Your erector spinae contract to stabilize your back.'),
           ('barbell-good-morning', 5, 'In order to allow your lower back to adapt to the barbell good morning exercise, start with a light weight and add more weight in a gradual manner.'),
           ('barbell-good-morning', 6, 'In hip-hinge exercises such as the barbell good morning, different muscles will be emphasized depending on how much your knees are flexed. If your knees are extended or only slightly flexed, as in the case of the barbell good morning, then your hamstrings will be emphasized over your gluteus maximus. On the other hand, if your knees are flexed, as in the case of the bent-knee barbell good morning, then your gluteus maximus will be emphasized over your hamstrings.'),
           ('barbell-good-morning', 7, 'See also the Smith machine bent-knee good morning.'),

           ('barbell-bent-knee-good-morning', 1, 'For your safety, do not flex your hips beyond feeling a mild stretch in your hamstrings. Depending on the flexibility of your hamstrings, you may need to flex your knees more in order to lower your torso to the desired level.'),
           ('barbell-bent-knee-good-morning', 2, 'Maintain a neutral back and neck when performing this exercise. Do not keep looking forward when lowering your torso.'),
           ('barbell-bent-knee-good-morning', 3, 'Start with a light weight and add more weight gradually. This will allow your lower back time to adapt.'),
           ('barbell-bent-knee-good-morning', 4, 'The barbell bent-knee good morning is a hip-hinge exercise since it primarily utilizes hip extension. Even though there is movement in the knees, it is also classified as an isolation exercise because the movement in the knees is (or should be) minimal.'),
           ('barbell-bent-knee-good-morning', 5, 'The two main muscle groups that are involved in hip extension are the gluteus maximus and hamstrings. In the barbell bent-knee good morning, the gluteus maximus is emphasized over the hamstrings. This is because, as the knees flex, the hamstrings become loose, which forces the gluteus maximus to contribute more to the movement. On the other hand, if the knees were kept extended or very slightly flexed, such as with the barbell good morning, the hamstrings would be emphasized over the gluteus maximus.'),
           ('barbell-bent-knee-good-morning', 6, 'An alternative to the barbell bent-knee good morning is the Smith machine bent-knee good morning.'),
           ('barbell-bent-knee-good-morning', 7, 'See also the seated barbell bent-knee good morning.'),

           ('barbell-sumo-romanian-deadlift', 1, 'The target muscle for the Throughout the exercise, ensure your arms and back are neutral, your chest is out and your shoulders are back.'),
           ('barbell-sumo-romanian-deadlift', 2, 'For the safety of your ankles and knees, your feet and knees must point in the same direction. Do not allow your knees to cave in as you lower the barbell. Push them out to the sides.'),
           ('barbell-sumo-romanian-deadlift', 3, 'Do not lean backwards when you reach the top of the movement.'),
           ('barbell-sumo-romanian-deadlift', 4, 'Keep the barbell close to your body to improve mechanical leverage.'),
           ('barbell-sumo-romanian-deadlift', 5, 'Begin with a light weight. Gradually increase the weight when you are familiar with proper form.'),
           ('barbell-sumo-romanian-deadlift', 6, 'To improve your grip, you may try using a mixed grip (one hand over, one hand under).'),
           ('barbell-sumo-romanian-deadlift', 7, 'The barbell sumo Romanian deadlift combines the stance of the barbell sumo deadlift and the movement pattern of the barbell Romanian deadlift.'),
           ('barbell-sumo-romanian-deadlift', 8, 'This exercise is also known as the barbell sumo RDL.'),

           ('chin-up', 1, 'Use the chin-up, a major compound bodyweight exercise, to build the size and strength of your upper body, especially your back and elbow flexors.'),
           ('chin-up', 2, 'The chin-up activates the biceps brachii more than the pull-up does because the forearms are supinated with the chin-up but pronated with the pull-up.'),
           ('chin-up', 3, 'For best results, move through the full range of motion.'),
           ('chin-up', 4, 'Engage your core to keep your body straight throughout the exercise.'),
           ('chin-up', 5, 'To make the chin-up easier, use an assisted pull-up machine. If you have no access to an assisted pull-up machine, tie a long exercise/resistance band to the bar and place one foot inside the loop that the band creates.'),
           ('chin-up', 6, 'o make the chin-up more difficult, either use a dip belt with additional weight or hold a dumbbell between your feet.'),
           ('chin-up', 7 ,'If your wrists hurt, perform the close neutral-grip pull-up instead.'),

           ('kettlebell-deadlift', 1, 'The kettlebell deadlift is a fantastic compound exercise for strengthening your lower body and posterior chain muscles, making it important for functional fitness.'),
           ('kettlebell-deadlift', 2, 'If you are a beginner, use the kettlebell deadlift to work your way up to the barbell deadlift. Otherwise, you can use it as an auxiliary exercise to improve your barbell deadlift.'),
           ('kettlebell-deadlift', 3, 'This exercise is a great alternative for back pain.'),
           ('kettlebell-deadlift', 4, 'For the safety of your knees, keep your feet and knees pointing in the same direction.'),
           ('kettlebell-deadlift', 5, 'Placing the kettlebell between your feet keeps the weight within your base of support and lowers your center of gravity, making the kettlebell deadlift easier compared to the dumbbell deadlift and the barbell deadlift.'),

           ('leg-extension', 1, 'Position your knees at the same axis as the lever fulcrum.'),
           ('leg-extension', 2, 'As you raise the padded lever, do not allow your hips to curl up; keep your thighs in firm contact with the seat.'),
           ('leg-extension', 3, 'Do not go too heavy because it can be bad for your knees.'),
           ('leg-extension', 4, 'The leg extension exercise mainly develops your lower quads. To put more emphasis on your upper quads, as you raise your legs, point your toes forward (see video).'),
           ('leg-extension', 5, 'The exercise can also be performed with one leg at a time.'),
           ('leg-extension', 6, 'The leg extension should not be your primary quad exercise. There are far better options. The barbell squat, for example, builds your quads equally well, as well as simultaneously builds and strengthens many other muscle groups, strengthens your core, and helps you to develop functional strength. Use the leg extension only to warm up your quads, pre-exhaust them before squats, or flush them at the end of a leg workout.'),

           ('wheel-rollout', 1, 'Keep your arms almost straight.'),
           ('wheel-rollout', 2, 'Initially, you may not be able to roll out very far without your lower back sagging. That’s fine. As you keep practicing, you will be able to roll out increasingly farther.'),
           ('wheel-rollout', 3, 'The wheel rollout exercise is a little advanced. To build yourself up to it, you can start with the plank and graduate to the wheel rollout when ready. You can also make the exercise easier by performing it up an inclined surface.'),
           ('wheel-rollout', 4, 'To make the wheel rollout more difficult, wear a weighted vest or perform it standing.'),
           ('wheel-rollout', 5, 'If you don’t have a wheel, you can use an exercise ball or a barbell.'),
           ('wheel-rollout', 6, 'The wheel rollout is not an ab exercise because there is often either very little or no waist flexion. Most of the movement is in your hips and shoulders. Your abs and obliques usually only act as stabilizers. They contract isometrically to stabilize your waist.'),

           ('one-arm-bench-dip', 1, 'Leg muscles have been listed above as targets, synergists, and dynamic stabilizers with the assumption that the movement will be undertaken by both your arm and your leg. However, ideally, you should keep the involvement of your leg to a minimum and make your triceps do as much of the work as possible.'),
           ('one-arm-bench-dip', 2, 'Keep your elbow close to your body. Do not allow it to flare out.'),
           ('one-arm-bench-dip', 3, 'Do not lock out your elbow at the top of the press.'),
           ('one-arm-bench-dip', 4, 'Keep your body upright and your back straight.'),
           ('one-arm-bench-dip', 5, 'To make the one-arm bench dip easier, keep both feet on the floor.'),
           ('one-arm-bench-dip', 6, 'To make the exercise more difficult, extend your legs and rest both heels on the floor so that your body is supported only by your working arm.'),

           ('barbell-sumo-squat', 1, 'Keep your feet flat, and your feet and knees pointing in the same direction.'),
           ('barbell-sumo-squat', 2, 'Don’t allow your knees to cave in; keep them out.'),
           ('barbell-sumo-squat', 3, 'Use a power cage or a squat rack for safety.'),
           ('barbell-sumo-squat', 4, 'The wide stance of the barbell sumo squat is great for inner-thigh development. It also enhances the involvement of your gluteus maximus, but only if you lift heavy.'),
           ('barbell-sumo-squat', 5, 'Your erector spinae work as important stabilizers if you lift heavy. Your hamstrings are not significantly activated. As with all types of squat, they mainly act to stabilize your knees.'),

           ('weighted-one-leg-hip-thrust', 1, 'You can keep your free leg either extended or flexed.'),
           ('weighted-one-leg-hip-thrust', 2, 'To prevent the bench from tipping over, place it against a wall.'),
           ('weighted-one-leg-hip-thrust', 3, 'Do not allow your back to arch or your pelvis to tilt. Keep your torso rigid.'),
           ('weighted-one-leg-hip-thrust', 4, 'Instead of a weight plate, you can use a dumbbell.'),
           ('weighted-one-leg-hip-thrust', 5, 'Avoid using a very heavy weight with the weighted one-leg hip thrust because it can place too much rotational force (torque) on your lower back (lumbar spine). If you want to do very heavy hip thrusts, use the barbell hip thrust.'),

           ('bodyweight-squat', 1, 'Keep your knees and feet pointing in the same direction, and your feet flat on the floor.'),
           ('bodyweight-squat', 2, 'Keep your back straight, head up, and torso upright.'),
           ('bodyweight-squat', 3, 'The bodyweight squat is great for learning the very basics of squat form, such as how to keep your torso upright and head up as you descend.'),
           ('bodyweight-squat', 4, 'Make the bodyweight squat more difficult by pulsing at the bottom of the squat.'),
           ('bodyweight-squat', 5, 'The bodyweight squat is also known as the air squat.'),

           ('lunge', 1, 'Keep your torso upright and facing forward.'),
           ('lunge', 2, 'Keep your feet and knees facing forward, in the same direction.'),
           ('lunge', 3, 'Make sure that your lunge is large enough that the knee of your front leg does not move in front of the toes of your front leg. This will protect your ankles.'),
           ('lunge', 4, 'The larger your lunge is, the more emphasis you will place on your gluteus maximus instead of your quadriceps.'),
           ('lunge', 5, 'The lunge is a brilliant exercise, helping you to develop coordination, balance, and the unilateral (one-sided) functional strength of your lower body.'),
           ('lunge', 6, 'Make the lunge exercise more difficult by holding dumbbells in your hands (see the dumbbell lunge). If you want to place extra emphasis on your gluteus maximus, see the dumbbell forward-leaning lunge.'),

           ('dumbbell-box-squat', 1, 'Keep your torso upright, your knees out, your shins vertical, and your feet flat'),
           ('dumbbell-box-squat', 2, 'Keep your feet and knees pointing in the same direction.'),
           ('dumbbell-box-squat', 3, 'Control the movement all the way down to the box or bench. Do not sit down; just pause. Sitting down will lead to spinal compression.'),
           ('dumbbell-box-squat', 4, 'Drive through your heels when you spring upward, and do not rock forward.'),
           ('dumbbell-box-squat', 5, 'The purpose of using the box or bench in the dumbbell box squat or in any box squat exercise is to eliminate the ‘stretch reflex’, which occurs at the bottom of the squat and aids in the concentric (ascending) phase of the repetition. Eliminating the stretch reflex makes the exercise more difficult and therefore allows you to overload the squat movement pattern with the use of less weight.'),
           ('dumbbell-box-squat', 6, 'By eliminating the stretch reflex, this exercise will allow you to improve your squat strength, which will carry over to all of your other squatting exercises.'),
           ('dumbbell-box-squat', 7, 'As less weight can be used, this exercise is more suitable than other squatting exercises for people with knee problems.'),
           ('dumbbell-box-squat', 8, 'The dumbbell box squat (or any type of box squat) is not suitable for beginners, who first have to learn how to perform the regular dumbbell and barbell squats.'),
           ('dumbbell-box-squat', 9, 'The height of the box or bench that you use should allow you to descend until your thighs are at least parallel with the floor.'),
           ('dumbbell-box-squat', 10, 'One benefit the dumbbell box squat has over the barbell box squat is that you can perform it anywhere with no need for a spotter.'),

           ('smith-machine-squat', 1, 'Keep your feet flat and your torso upright.'),
           ('smith-machine-squat', 2, 'Keep your feet and knees pointing in the same direction.'),
           ('smith-machine-squat', 3, 'At the bottom of the squat, make sure that your knees remain behind your toes.'),
           ('smith-machine-squat', 4, 'At the bottom of the squat, make sure that your knees remain behind your toes.'),
           ('smith-machine-squat', 5, 'Although great for allowing you to safely squat heavy weights, the Smith machine squat is not as great an exercise as is the barbell squat because the latter recruits more stabilizer muscles and helps to improve your balance.'),

           ('seated-dumbbell-one-leg-calf-raise', 1, 'Engage your core to keep your torso upright throughout the exercise.'),
           ('seated-dumbbell-one-leg-calf-raise', 2, 'Your calves are made up of the gastrocnemius and soleus muscles. The seated dumbbell one-leg calf raise places more stress on the soleus than it does on the gastrocnemius.'),
           ('seated-dumbbell-one-leg-calf-raise', 3, 'If you find yourself having to lean back or laterally flex at the waist when performing the seated dumbbell one-leg calf raise, your dumbbell may be too heavy for you. Consider using a lighter dumbbell to perform the exercise with correct form.'),
           ('seated-dumbbell-one-leg-calf-raise', 4, 'If there are size and strength differences between your calves, perform this exercise first on your smaller or weaker calf, and do not perform more reps on your stronger calf. This will allow your weaker calf to catch up in strength.'),
           ('seated-dumbbell-one-leg-calf-raise', 5, 'The seated dumbbell one-leg calf raise may also be performed with both legs simultaneously, but doing it one leg at a time is recommended to execute it as properly and safely as possible.'),
           ('seated-dumbbell-one-leg-calf-raise', 6, 'The seated dumbbell one-leg calf raise can be used as an alternative to the machine seated one-leg calf raise if you do not have access to the seated calf raise machine.'),

           ('dumbbell-overhead-squat', 1, 'Keep your head facing forward, your torso neutral and your arms almost fully extended throughout the exercise.'),
           ('dumbbell-overhead-squat', 2, 'For the safety of your ankles and knees, make sure that your toes and knees are pointing in the same direction.'),
           ('dumbbell-overhead-squat', 3, 'The dumbbell overhead squat is great for overloading your lower body (especially your quadriceps and glutes), strengthening your core, and improving your balance.'),
           ('dumbbell-overhead-squat', 4, 'Start with light weights until you master proper form and balance. You can gradually increase the weight you’re lifting as you get more familiar with performing the dumbbell overhead squat.'),
           ('dumbbell-overhead-squat', 5, 'You can also look into the following squat exercises that use dumbbells: dumbbell squat, dumbbell box squat, dumbbell sumo squat.'),

           ('bulgarian-split-squat', 1, 'Use the Bulgarian split squat to develop unilateral leg strength, enhance your balance and coordination, and improve your lunges and squats.'),
           ('bulgarian-split-squat', 2, 'Keep your front knee and foot aligned and facing forward. Your knee should not move in front of your toes when you squat.'),
           ('bulgarian-split-squat', 3, 'Throughout the exercise, keep your torso upright and your back neutral.'),
           ('bulgarian-split-squat', 4, 'The wider you split your legs, the more you will emphasize your glutes. However, the quadriceps will remain as the target muscle group.'),
           ('bulgarian-split-squat', 5, 'Perform the Bulgarian split squat with your weaker leg first and do not perform more repetitions with your stronger leg. This will promote equal strength between your legs.'),
           ('bulgarian-split-squat', 6, 'To make this exercise more difficult, perform it with dumbbells or barbells, as in the dumbbell split squat and barbell Bulgarian split squat.'),


           ('one-leg-hip-thrust', 1, 'The one-leg hip thrust and other hip-thrust exercises are fantastic for isolating and building the glutes.'),
           ('one-leg-hip-thrust', 2, 'Keep your neck and back neutral throughout the exercise.'),
           ('one-leg-hip-thrust', 3, 'Place the bench against a wall to prevent it from tipping over.'),
           ('one-leg-hip-thrust', 4, 'You can keep your free leg either flexed or extended. Extending your free leg will make the one-leg hip thrust slightly harder since it pushes your center of gravity forward. Pushing your center of gravity forward means it is less within your base of support thus requiring slightly more strength and control from your muscles.'),
           ('one-leg-hip-thrust', 5, 'Make the one-leg hip thrust more challenging by performing it with weights, such as in the weighted one-leg hip thrust and the barbell one-leg hip thrust.'),

           ('double-kettlebell-front-squat', 1, 'While this is primarily a lower body strengthening exercise, the double kettlebell front squat activates more stabilizer muscles in the core compared to the barbell front squat. Positioning the kettlebells anteriorly (in front of your shoulders) forces your core muscles to stabilize even more in order to maintain an upright torso.'),
           ('double-kettlebell-front-squat', 2, 'Keep your elbows facing forward to help with stability.'),
           ('double-kettlebell-front-squat', 3, 'For the safety of your knees, keep your feet and knees pointing in the same direction.'),
           ('double-kettlebell-front-squat', 4, 'See also the barbell front box squat.'),

           ('dumbbell-goblet-split-squat', 1, 'As with all split squat exercises, use the dumbbell goblet split squat to develop unilateral lower-body strength and enhance your balance.'),
           ('dumbbell-goblet-split-squat', 2, 'Perform the exercise in a controlled manner. Do not bounce as this can cause injury to your knees.'),
           ('dumbbell-goblet-split-squat', 3, 'Make sure that your knees and feet are facing the same direction.'),
           ('dumbbell-goblet-split-squat', 4, 'If you hold the dumbbell too far out, you are targeting your biceps and deltoids instead of the quadriceps. Keep the dumbbell against your chest throughout the exercise.'),
           ('dumbbell-goblet-split-squat', 5, 'Compared to the dumbbell split squat, the goblet dumbbell split squat is slightly more challenging since holding the dumbbell to your chest moves your center of gravity higher, whereas holding the dumbbells to your sides, as in the dumbbell split squat, moves your center of gravity lower.'),
           ('dumbbell-goblet-split-squat', 6, 'See also the barbell split squat and the barbell-between-legs split squat.'),

           ('sit-up', 1, 'Perform the sit-up in a controlled manner. Do not thump your back on the floor when lowering your torso back to the starting position.'),
           ('sit-up', 2, 'Do not pull on your neck. Keep it neutral throughout the exercise.'),
           ('sit-up', 3, 'Performing the sit-up on a mat may help to prevent any bruising of your tailbone or lower back.'),
           ('sit-up', 4, 'To keep your feet planted flat on the floor, you may tuck them under a bench or have someone hold them down.'),
           ('sit-up', 5, 'Varying the position of your arms can make the sit-up either easier or harder. Your center of gravity is altered depending on where you place your arms. The farther your center of gravity is from the joint that serves as the axis of the movement (in this case, the hips), the harder it becomes.'),

           ('crunch', 1, 'Keep the movement slow and controlled. Don’t use momentum.'),
           ('crunch', 2, 'Keep your neck straight.'),
           ('crunch', 3, 'To make the crunch more difficult, stretch your arms out overhead and cross your palms. You can also hold a plate behind your head, or perform the exercise on a decline bench.'),
           ('crunch', 4, 'To make the exercise easier, cross your arms over your chest.'),
           ('crunch', 5, 'The crunch is not an effective ab exercise. The most effective exercises for the abs and obliques were found to be the captain’s chair (which is essentially the same as the hanging leg and hip raise) and the bicycle crunch.'),

           ('front-plank', 1, 'The front plank is a brilliant bodyweight exercise that helps you to develop the strength and stability of your core. Your muscles are exercised isometrically.'),
           ('front-plank', 2, 'Do not let your lower back sag or your butt rise. Ensure your body is straight and rigid.'),
           ('front-plank', 3, 'Keep your glutes and core muscles contracted.'),
           ('front-plank', 4, 'Keep your shoulders down, maximizing the distance between your shoulders and ears.'),
           ('front-plank', 5, 'To make the front plank easier, perform it on bent knees instead of toes.'),
           ('front-plank', 6, 'To make the exercise more difficult, raise one leg off the ground and hold this position before repeating with the other leg. See the one-leg front plank.'),
           ('front-plank', 7, 'To challenge your balance, try the stability ball front plank.'),

           ('lying-side-hip-raise', 1, 'Keep your legs and body straight.'),
           ('lying-side-hip-raise', 2, 'Make the lying side hip raise exercise easier by bending your knees and supporting your lower body on the side of your knee instead of the side of your foot.'),
           ('lying-side-hip-raise', 3, 'Make the exercise more difficult by holding a weight on your hip.'),
           ('lying-side-hip-raise', 4, 'Don’t allow your neck to rest on your shoulder. Keep a space between the two by extending your shoulder.'),
           ('lying-side-hip-raise', 5, 'Also known as the side plank hip raise, side plank hip drop, side bridge hip raise, and hip-up.'),

           ('weighted-hanging-leg-and-hip-raise', 1, 'Master proper form by performing the hanging leg and hip raise first before attempting the weighted hanging leg and hip raise. Poor form coupled with the extra weight may lead to injury.'),
           ('weighted-hanging-leg-and-hip-raise', 2, 'Begin with light weights and gradually add more weight as your body becomes accustomed to the exercise.'),
           ('weighted-hanging-leg-and-hip-raise', 3, 'Perform the exercise in a controlled manner. Do not swing or use momentum.'),
           ('weighted-hanging-leg-and-hip-raise', 4, 'To dynamically activate your abdominals and obliques, be sure to flex your waist at the top of the movement. Otherwise, your abs and obliques will only work as stabilizers.'),
           ('weighted-hanging-leg-and-hip-raise', 5, 'Flexing your waist is what makes the hanging leg and hip raise different from the hanging leg raise, which primarily works the hip flexors, especially the iliopsoas.'),
           ('weighted-hanging-leg-and-hip-raise', 6, 'A good alternative to the weighted hanging leg and hip raise is the weighted captain’s chair leg and hip raise. The captain’s chair provides support to your lower back, which helps to prevent it from hyperextending.'),

           ('frog-crunch', 1, 'Keep your legs relaxed and your lower back pressed against the floor.'),
           ('frog-crunch', 2, 'Keep your neck neutral. The same amount of space between your chin and sternum should remain throughout the movement.'),
           ('frog-crunch', 3, 'Keep the movement slow and under control. Avoid using momentum.'),
           ('frog-crunch', 4, 'The point of the frog crunch is that by keeping your legs relaxed in the frog position, you reduce the extent to which your hip-flexing muscles, such as your rectus femoris and iliopsoas, can contribute to the exercise. In so doing, you help to isolate your rectus abdominis and obliques.'),
           ('frog-crunch', 5, 'See also the frog crunch with leg raise.'),

           ('frog-crunch-with-leg-raise', 1, 'Keep your feet off the floor and your lower back pressed against the floor.'),
           ('frog-crunch-with-leg-raise', 2, 'Keep your neck neutral; there should be space between your chin and sternum.'),
           ('frog-crunch-with-leg-raise', 3, 'Make the frog crunch with leg raise more difficult by straightening your legs before each crunch.'),

           ('bent-knee-oblique-v-up', 1, 'Keep the movement slow and under control.'),
           ('bent-knee-oblique-v-up', 2, 'Do not pull on your head. Keep your neck neutral.'),
           ('bent-knee-oblique-v-up', 3, 'Keep your legs off the floor.'),
           ('bent-knee-oblique-v-up', 4, 'To make the exercise more difficult, extend your legs.'),
           ('bent-knee-oblique-v-up', 5, 'The bent-knee oblique v-up can be difficult for beginners, who should start with more basic core exercises, such as the twisting crunch.'),
           ('bent-knee-oblique-v-up', 6, 'The bent-knee oblique v-up is also known as the side sit-up, oblique sit-up, and side jackknife (although these names can also sometimes be used for other, similar exercises).'),

           ('side-plank-hip-adduction', 1, 'The side plank hip adduction is a decent exercise that you can use at home or at the gym to strengthen your core, work your inner thighs, and strengthen the lateral flexion movement pattern of your spine.'),
           ('side-plank-hip-adduction', 2, 'Make sure you get full hip adduction and lateral flexion of your spine.'),
           ('side-plank-hip-adduction', 3, 'Make the exercise easier by resting your knee instead of your foot on the bench.'),
           ('side-plank-hip-adduction', 4, 'Make it more difficult by holding a weight plate on your hip.'),
           ('side-plank-hip-adduction', 5, 'Keep your elbow directly under your shoulder.'),
           ('side-plank-hip-adduction', 6, 'Also known as the hip adduction oblique bridge.'),

           ('hanging-leg-hip-raise', 1, 'Make sure that you’re not just raising your knees. After raising your knees, you must also flex your abdomen to raise your knees even higher. If you do not flex your abdomen, your abs and obliques will only function as stabilizers.'),
           ('hanging-leg-hip-raise', 2, 'Do not swing or use momentum.'),
           ('hanging-leg-hip-raise', 3, 'Keep your lower back as straight as possible throughout the exercise. The exercise is best performed with your lower back pressed against a padded surface for support (see video). Instead of hanging from a bar with an unsupported lower back, use a captain’s chair if one is available.'),
           ('hanging-leg-hip-raise', 4, 'The hanging leg and hip raise is essentially the same as the captain’s chair leg and hip raise, an exercise that, in one classic study, was found to be the most effective at activating the obliques and the second most effective at activating the abs.'),
           ('hanging-leg-hip-raise', 5, 'To make the hanging leg and hip raise exercise easier, perform it lying on your back (lying leg and hip raise).'),
           ('hanging-leg-hip-raise', 6, 'To make it more difficult, straighten your legs (hanging straight leg and hip raise), or hold a dumbbell between your feet (weighted hanging leg and hip raise).')

           ;



